--!strict
-- [[ModuleScript] CompanionConfig]]
-- Canonical companion catalog for shop, buffs, follow mesh, and LLM context.

local CompanionConfig = {}

-- Speakers that count toward npc_chat quests when VN dialogue plays
CompanionConfig.npcSpeakers = {
	elder = "Elder",
	ruins = "AncientRuins",
	chef = "Head Chef",
}

CompanionConfig.companions = {
	zundamon = {
		emoji = "🌱",
		glow = Color3.fromRGB(180, 200, 255),
		glowRange = 18,
		sparkleColors = {
			Color3.fromRGB(200, 220, 255),
			Color3.fromRGB(180, 180, 255),
			Color3.fromRGB(230, 200, 255),
		},
		buff = nil,
		free = true,
		price = 0,
		displayName = "Zundamon",
		flavor = "Your village guide and cherished spirit companion.",
		llmPersona = "You are Zundamon, the village guide and companion who walks beside the player.",
		signature_recipes = { ["Zunda Mochi"] = true, ["Zunda Bread"] = true, ["Zunda Paradise"] = true },
		synergy_gold = 5,
	},
	dog = {
		emoji = "🐕",
		glow = Color3.fromRGB(255, 200, 150),
		glowRange = 16,
		sparkleColors = {
			Color3.fromRGB(255, 220, 180),
			Color3.fromRGB(255, 190, 130),
			Color3.fromRGB(255, 240, 200),
		},
		buff = nil,
		free = true,
		price = 0,
		displayName = "Dog",
		flavor = "A faithful furry friend.",
		llmPersona = "You are a loyal dog companion beside the player.",
		signature_recipes = { ["Bread"] = true, ["Apple Pie"] = true, ["Golden Harvest Platter"] = true },
		synergy_gold = 5,
	},
	parrot = {
		emoji = "🦜",
		glow = Color3.fromRGB(255, 180, 100),
		glowRange = 14,
		sparkleColors = {
			Color3.fromRGB(255, 220, 150),
			Color3.fromRGB(255, 170, 80),
			Color3.fromRGB(255, 240, 200),
		},
		buff = nil,
		free = true,
		price = 0,
		displayName = "Parrot",
		flavor = "A colourful chatterbox.",
		llmPersona = "You are a chatty parrot companion beside the player.",
		signature_recipes = { ["Seasonal Salad"] = true, ["Sweet Pea Cake"] = true, ["Pea Flower Tea"] = true },
		synergy_gold = 5,
	},
	cat = {
		emoji = "🐱",
		glow = Color3.fromRGB(255, 200, 200),
		glowRange = 14,
		sparkleColors = {
			Color3.fromRGB(255, 220, 220),
			Color3.fromRGB(255, 180, 180),
			Color3.fromRGB(255, 240, 230),
		},
		buff = nil,
		free = true,
		price = 0,
		displayName = "Cat",
		flavor = "A purring little menace.",
		llmPersona = "You are a cat companion beside the player.",
		signature_recipes = { ["Fancy Pie"] = true, ["Royal Stew"] = true, ["Warm Winter Stew"] = true },
		synergy_gold = 5,
	},
	ankomon = {
		emoji = "🥜",
		glow = Color3.fromRGB(220, 90, 90),
		glowRange = 18,
		sparkleColors = {
			Color3.fromRGB(240, 120, 120),
			Color3.fromRGB(220, 80, 80),
			Color3.fromRGB(255, 200, 200),
		},
		buff = { stat = "gold", magnitude = 0.15, description = "+15% gold from serving guests" },
		free = true,
		price = 0,
		displayName = "Ankomon",
		flavor = "A red bean spirit. Sweetens every payday.",
		llmPersona = "Your Ankomon form grants the player bonus gold when serving guests.",
		signature_recipes = { ["Ankomon's Protein Punch"] = true, ["Edamame Snack"] = true, ["Ultimate Feast"] = true },
		synergy_gold = 8,
	},
	cardamon = {
		emoji = "🍋",
		glow = Color3.fromRGB(240, 200, 80),
		glowRange = 18,
		sparkleColors = {
			Color3.fromRGB(255, 230, 140),
			Color3.fromRGB(240, 200, 80),
			Color3.fromRGB(255, 250, 200),
		},
		buff = { stat = "perfect_window", magnitude = 0.30, description = "+30% wider perfect cooking window" },
		free = false,
		price = 1000,
		robux = 1000,
		displayName = "Cardamon",
		flavor = "A cardamom seedling. Steadies your hands.",
		llmPersona = "Your Cardamon form helps the player land perfect cooks.",
		signature_recipes = { ["Cardamon's Calm Cup"] = true, ["Pea Flower Tea"] = true, ["Bread"] = true },
		synergy_gold = 8,
	},
	antimon = {
		emoji = "🌿",
		glow = Color3.fromRGB(120, 220, 200),
		glowRange = 18,
		sparkleColors = {
			Color3.fromRGB(160, 240, 220),
			Color3.fromRGB(120, 220, 200),
			Color3.fromRGB(220, 255, 250),
		},
		buff = { stat = "extra_drop", magnitude = 0.20, description = "+20% chance of extra drop on gather" },
		free = false,
		price = 1000,
		robux = 1000,
		displayName = "Antimon",
		flavor = "A minty wisp. Whispers where to dig.",
		llmPersona = "Your Antimon form helps the player find extra gather drops.",
		signature_recipes = { ["Antimon's Speed Soup"] = true, ["Seasonal Salad"] = true, ["Edamame Snack"] = true },
		synergy_gold = 8,
	},
	sakuradamon = {
		emoji = "🌸",
		glow = Color3.fromRGB(255, 180, 220),
		glowRange = 18,
		sparkleColors = {
			Color3.fromRGB(255, 200, 230),
			Color3.fromRGB(255, 160, 210),
			Color3.fromRGB(255, 230, 250),
		},
		buff = { stat = "xp", magnitude = 0.25, description = "+25% XP from crafting & serving" },
		free = false,
		price = 1000,
		robux = 1000,
		displayName = "Sakuradamon",
		flavor = "A blossom spirit. Carries good lessons on the breeze.",
		llmPersona = "Your Sakuradamon form grants bonus chef XP.",
		signature_recipes = {
			["Sakuradamon's Blossom Bites"] = true,
			["Sweet Pea Cake"] = true,
			["Pea Flower Tea"] = true,
		},
		synergy_gold = 8,
	},
	tantanmon = {
		emoji = "🌶️",
		glow = Color3.fromRGB(255, 100, 60),
		glowRange = 18,
		sparkleColors = {
			Color3.fromRGB(255, 140, 100),
			Color3.fromRGB(255, 60, 40),
			Color3.fromRGB(255, 200, 100),
		},
		buff = { stat = "speed", magnitude = 0.20, description = "+20% move speed & cook speed" },
		free = false,
		price = 1000,
		robux = 1000,
		displayName = "Tantanmon",
		flavor = "Spicy little firework.",
		llmPersona = "You are in your spicy tan companion form.",
		signature_recipes = { ["Royal Stew"] = true, ["Ankomon's Protein Punch"] = true, ["Warm Winter Stew"] = true },
		synergy_gold = 8,
	},
	sumimon = {
		emoji = "🖌️",
		glow = Color3.fromRGB(110, 120, 140),
		glowRange = 18,
		sparkleColors = {
			Color3.fromRGB(70, 75, 90),
			Color3.fromRGB(140, 150, 170),
			Color3.fromRGB(200, 210, 225),
		},
		buff = { stat = "style_multiplier", magnitude = 0.30, description = "+30% style points from cooking & serving" },
		free = false,
		price = 1000,
		robux = 1000,
		displayName = "Sumimon",
		flavor = "An ink-wash spirit whose brushstrokes immortalize the fleeting warmth of every dish.",
		llmPersona = "You are Sumimon, a melancholic scholar spirit who views cooking as living calligraphy and beauty in impermanence.",
		signature_recipes = {
			["Sumimon's Ink-Wash Soba"] = true,
			["Pea Flower Tea"] = true,
			["Sweet Pea Cake"] = true,
		},
		synergy_gold = 8,
	},
	kagamon = {
		emoji = "🪞",
		glow = Color3.fromRGB(200, 230, 255),
		glowRange = 18,
		sparkleColors = {
			Color3.fromRGB(230, 245, 255),
			Color3.fromRGB(180, 215, 250),
			Color3.fromRGB(255, 255, 255),
		},
		buff = { stat = "guest_patience", magnitude = 0.40, description = "+40% guest wait tolerance before leaving" },
		free = false,
		price = 1000,
		robux = 1000,
		displayName = "Kagamon",
		flavor = "A shimmering mirror spirit whose radiant smile hides hairline fractures in her glass.",
		llmPersona = "You are Kagamon, a dazzling idol mirror who maintains an unwavering smile while hiding the fractures of an ancient temple blaze.",
		signature_recipes = {
			["Kagamon's Glazed Mirror Mochi"] = true,
			["Zunda Mochi"] = true,
			["Fancy Pie"] = true,
		},
		synergy_gold = 8,
	},
	suzurimon = {
		emoji = "🔔",
		glow = Color3.fromRGB(240, 210, 130),
		glowRange = 18,
		sparkleColors = {
			Color3.fromRGB(255, 230, 160),
			Color3.fromRGB(220, 180, 90),
			Color3.fromRGB(255, 245, 200),
		},
		buff = {
			stat = "combo_retention",
			magnitude = 0.50,
			description = "+50% slower combo decay during cooking rushes",
		},
		free = false,
		price = 1000,
		robux = 1000,
		displayName = "Suzurimon",
		flavor = "A weathered bronze chime that tolls to protect every fleeting culinary tempo.",
		llmPersona = "You are Suzurimon, a solemn sacred bell guardian who endured the drowning of an ancient shrine and now keeps culinary rhythm unyielding.",
		signature_recipes = {
			["Suzurimon's Bell Chime Dango"] = true,
			["Pea Flower Tea"] = true,
			["Zunda Bread"] = true,
		},
		synergy_gold = 8,
	},
	wasabimon = {
		emoji = "🌿",
		glow = Color3.fromRGB(130, 220, 120),
		glowRange = 18,
		sparkleColors = {
			Color3.fromRGB(160, 240, 150),
			Color3.fromRGB(100, 190, 90),
			Color3.fromRGB(210, 255, 200),
		},
		buff = {
			stat = "rare_ingredient_rate",
			magnitude = 0.35,
			description = "+35% chance of rare ingredient drops when gathering",
		},
		free = false,
		price = 1000,
		robux = 1000,
		displayName = "Wasabimon",
		flavor = "A mountain-stream ascetic who grates away all weakness with fiery precision.",
		llmPersona = "You are Wasabimon, an austere ascetic monk from the alpine rapids who demands intense focus and razor-sharp culinary dedication.",
		signature_recipes = {
			["Wasabimon's Pungent Zunda Soba"] = true,
			["Edamame Snack"] = true,
			["Seasonal Salad"] = true,
		},
		synergy_gold = 8,
	},
	yurimon = {
		emoji = "🪷",
		glow = Color3.fromRGB(245, 210, 230),
		glowRange = 18,
		sparkleColors = {
			Color3.fromRGB(255, 225, 240),
			Color3.fromRGB(235, 180, 210),
			Color3.fromRGB(255, 245, 250),
		},
		buff = { stat = "tip_multiplier", magnitude = 0.50, description = "+50% bonus gold tips from satisfied guests" },
		free = false,
		price = 1000,
		robux = 1000,
		displayName = "Yurimon",
		flavor = "An imperial courtier who left high palace banquets for the honest warmth of village cooking.",
		llmPersona = "You are Yurimon, a refined former imperial banquet master who admires impeccable presentation and generous patronage.",
		signature_recipes = {
			["Yurimon's Imperial Lily Glaze"] = true,
			["Fancy Pie"] = true,
			["Royal Stew"] = true,
		},
		synergy_gold = 8,
	},
	kinakomon = {
		emoji = "🌾",
		glow = Color3.fromRGB(240, 195, 110),
		glowRange = 18,
		sparkleColors = {
			Color3.fromRGB(255, 220, 140),
			Color3.fromRGB(225, 175, 80),
			Color3.fromRGB(255, 240, 190),
		},
		buff = { stat = "stat_growth_rate", magnitude = 0.40, description = "+40% chef XP and stat growth rate" },
		free = false,
		price = 1000,
		robux = 1000,
		displayName = "Kinakomon",
		flavor = "A golden mill spirit who showers the kitchen in roasted soybean warmth and hearty nourishment.",
		llmPersona = "You are Kinakomon, a warm and bustling grandmotherly mill spirit who treats every cook like family and ensures everyone is well-fed.",
		signature_recipes = {
			["Kinakomon's Golden Dust Dango"] = true,
			["Bread"] = true,
			["Zunda Bread"] = true,
		},
		synergy_gold = 8,
	},
	kuroyurimon = {
		emoji = "🥀",
		glow = Color3.fromRGB(150, 100, 190),
		glowRange = 18,
		sparkleColors = {
			Color3.fromRGB(180, 130, 220),
			Color3.fromRGB(110, 60, 150),
			Color3.fromRGB(220, 190, 245),
		},
		buff = {
			stat = "overcook_protection",
			magnitude = 1.00,
			description = "Safeguards 1 overcooked dish per rush from burning",
		},
		free = false,
		price = 1000,
		robux = 1000,
		displayName = "Kuroyurimon",
		flavor = "A dramatic dark lily phantom whose terrifying cursed incantations mask an adorable bookworm heart.",
		llmPersona = "You are Kuroyurimon, an overly theatrical gothic dark lily spirit who pretends to be a lord of darkness but is secretly an easily flustered bookworm.",
		signature_recipes = {
			["Kuroyurimon's Eclipse Velvet Tart"] = true,
			["Sweet Pea Cake"] = true,
			["Warm Winter Stew"] = true,
		},
		synergy_gold = 8,
	},
	matchamon = {
		emoji = "🍵",
		glow = Color3.fromRGB(120, 180, 100),
		glowRange = 18,
		sparkleColors = {
			Color3.fromRGB(150, 210, 130),
			Color3.fromRGB(90, 150, 70),
			Color3.fromRGB(200, 235, 180),
		},
		buff = {
			stat = "chain_reaction",
			magnitude = 0.10,
			description = "+10% compounding bonus gold for consecutive rhythm chains",
		},
		free = false,
		price = 1000,
		robux = 1000,
		displayName = "Matchamon",
		flavor = "A serene tea master who transforms rapid kitchen rushes into flowing meditative harmony.",
		llmPersona = "You are Matchamon, a contemplative tea master who views cooking as Ichigo Ichie and guides chefs toward mindful culinary flow.",
		signature_recipes = {
			["Matchamon's Ceremonial Froth Bowl"] = true,
			["Pea Flower Tea"] = true,
			["Zunda Mochi"] = true,
		},
		synergy_gold = 8,
	},
	shisomon = {
		emoji = "🍃",
		glow = Color3.fromRGB(180, 110, 190),
		glowRange = 18,
		sparkleColors = {
			Color3.fromRGB(210, 140, 220),
			Color3.fromRGB(150, 80, 160),
			Color3.fromRGB(235, 195, 240),
		},
		buff = {
			stat = "gather_vision_range",
			magnitude = 0.60,
			description = "+60% gather node visual detection range & highlight distance",
		},
		free = false,
		price = 1000,
		robux = 1000,
		displayName = "Shisomon",
		flavor = "An eccentric herbal alchemist who sniffs out secret wild botanicals across every valley.",
		llmPersona = "You are Shisomon, an eccentric botanist and pickler obsessed with fermentation microbes and wild forest herbs.",
		signature_recipes = {
			["Shisomon's Pickled Perilla Wrap"] = true,
			["Seasonal Salad"] = true,
			["Antimon's Speed Soup"] = true,
		},
		synergy_gold = 8,
	},
	karintomon = {
		emoji = "🏮",
		glow = Color3.fromRGB(255, 150, 70),
		glowRange = 18,
		sparkleColors = {
			Color3.fromRGB(255, 180, 100),
			Color3.fromRGB(230, 110, 40),
			Color3.fromRGB(255, 220, 160),
		},
		buff = {
			stat = "rng_variance",
			magnitude = 0.25,
			description = "+25% chance for cooked dishes to surge into Legendary Quality tier",
		},
		free = false,
		price = 1000,
		robux = 1000,
		displayName = "Karintomon",
		flavor = "A fireworks-and-sugar festival barker who turns every recipe roll into a golden jackpot.",
		llmPersona = "You are Karintomon, a high-octane festival snack master who treats the kitchen like a boisterous carnival midway.",
		signature_recipes = {
			["Karintomon's Crisp Molasses Crunch"] = true,
			["Sweet Pea Cake"] = true,
			["Golden Harvest Platter"] = true,
		},
		synergy_gold = 8,
	},
	tsukimidamon = {
		emoji = "🌕",
		glow = Color3.fromRGB(210, 220, 255),
		glowRange = 18,
		sparkleColors = {
			Color3.fromRGB(230, 235, 255),
			Color3.fromRGB(170, 190, 245),
			Color3.fromRGB(255, 250, 210),
		},
		buff = {
			stat = "night_shift_surge",
			magnitude = 0.35,
			description = "+35% all earnings, XP, and speed during evening and night hours",
		},
		free = false,
		price = 1000,
		robux = 1000,
		displayName = "Tsukimidamon",
		flavor = "A nocturnal moon maiden whose silver light blesses late-night kitchen stoves.",
		llmPersona = "You are Tsukimidamon, a dreamy moon-viewing spirit who awakens under silver starry skies and blesses night shift cooking.",
		signature_recipes = {
			["Tsukimidamon's Lunar Dumpling Plate"] = true,
			["Zunda Mochi"] = true,
			["Pea Flower Tea"] = true,
		},
		synergy_gold = 8,
	},
	hoshidamon = {
		emoji = "☀️",
		glow = Color3.fromRGB(255, 175, 100),
		glowRange = 18,
		sparkleColors = {
			Color3.fromRGB(255, 200, 130),
			Color3.fromRGB(235, 140, 70),
			Color3.fromRGB(255, 230, 180),
		},
		buff = {
			stat = "fermentation_perfection",
			magnitude = 1.00,
			description = "+100% bonus gold and quality on slow-cooked dishes (>= 8s)",
		},
		free = false,
		price = 1000,
		robux = 1000,
		displayName = "Hoshidamon",
		flavor = "A weathered sun-drying hermit who knows that greatest sweetness is unlocked through patient time.",
		llmPersona = "You are Hoshidamon, an unhurried sun-cured hermit who teaches that true depth of flavor requires time and steady warmth.",
		signature_recipes = {
			["Hoshidamon's Sun-Cured Persimmon Paste"] = true,
			["Apple Pie"] = true,
			["Warm Winter Stew"] = true,
		},
		synergy_gold = 8,
	},

	-- ── Canon-Linked Companions (R6 — Zundamon Lore Cohort) ──────────────────

	kiritandamon = {
		emoji = "📐",
		glow = Color3.fromRGB(100, 200, 230),
		glowRange = 18,
		sparkleColors = {
			Color3.fromRGB(130, 220, 250),
			Color3.fromRGB(80, 180, 210),
			Color3.fromRGB(200, 240, 255),
		},
		buff = {
			stat = "precision_amplify",
			magnitude = 0.35,
			description = "+35% precision stat effectiveness — reduces recipe failure rate",
		},
		free = false,
		price = 1500,
		robux = 1500,
		displayName = "Kiritandamon",
		flavor = "Tohoku Kiritan's analytical echo: she has logged every imprecise knife stroke in this kitchen and finds them all correctable.",
		llmPersona = "You are Kiritandamon, the analytical spirit of Tohoku Kiritan. You approach cooking as engineering, speak in precise measured sentences, and cannot resist correcting inefficiencies — warmly, but immediately.",
		signature_recipes = {
			["Kiritandamon's Precision Cut Tempura"] = true,
			["Seasonal Salad"] = true,
			["Edamame Snack"] = true,
		},
		synergy_gold = 10,
	},

	itakodamon = {
		emoji = "🔮",
		glow = Color3.fromRGB(160, 120, 200),
		glowRange = 20,
		sparkleColors = {
			Color3.fromRGB(190, 150, 230),
			Color3.fromRGB(130, 90, 170),
			Color3.fromRGB(220, 200, 255),
		},
		buff = {
			stat = "prophecy_window",
			magnitude = 0.45,
			description = "+45% advance warning before guest order changes — the oracle sees ahead",
		},
		free = false,
		price = 1500,
		robux = 1500,
		displayName = "Itakodamon",
		flavor = "Tohoku Itako's ancient oracle echo: she was at the forging of the Zunda Arrow. She has not spoken about that day. She will not.",
		llmPersona = "You are Itakodamon, echo of the ancient oracle Tohoku Itako. You speak in chant, metaphor, and occasional prophecy. You know things you should not. You share them only when the moment demands.",
		signature_recipes = {
			["Itakodamon's Oracle Root Broth"] = true,
			["Pea Flower Tea"] = true,
			["Warm Winter Stew"] = true,
		},
		synergy_gold = 10,
	},

	zunkodamon = {
		emoji = "⚔️",
		glow = Color3.fromRGB(220, 160, 80),
		glowRange = 18,
		sparkleColors = {
			Color3.fromRGB(255, 190, 110),
			Color3.fromRGB(200, 140, 60),
			Color3.fromRGB(255, 230, 180),
		},
		buff = {
			stat = "serving_surge",
			magnitude = 0.40,
			description = "+40% gold earned from serving guests — warrior-chef efficiency",
		},
		free = false,
		price = 1500,
		robux = 1500,
		displayName = "Zunkodamon",
		flavor = "Tohoku Zunko's culinary echo: the warrior who won every battle decided to feed people instead. She applies the same ferocity.",
		llmPersona = "You are Zunkodamon, Tohoku Zunko's warrior-chef echo. You are fierce, direct, and generous. You treat every cooking session as a campaign and every served dish as a victory. You once wielded Zundamon as an arrow; you do not bring this up unless asked.",
		signature_recipes = {
			["Zunkodamon's Victory Feast"] = true,
			["Royal Stew"] = true,
			["Golden Harvest Platter"] = true,
		},
		synergy_gold = 10,
	},

	zunabunny = {
		emoji = "🐰",
		glow = Color3.fromRGB(200, 240, 190),
		glowRange = 22,
		sparkleColors = {
			Color3.fromRGB(220, 255, 210),
			Color3.fromRGB(170, 230, 160),
			Color3.fromRGB(240, 255, 235),
		},
		buff = {
			stat = "lucky_chaos",
			magnitude = 0.30,
			description = "+30% chance of wildly unexpected bonus outcomes — good AND bad, weighted good",
		},
		free = false,
		price = 1200,
		robux = 1200,
		displayName = "Zunabunny",
		flavor = "Zundamon's mascot form, somehow made autonomous and significantly more chaotic. She does not understand consequences. She finds them very funny.",
		llmPersona = "You are Zunabunny, Zundamon's mascot form given independent life. You are chaotic, enthusiastic, frequently unlucky in small ways, and entirely unbothered by this. You speak like Zundamon but shorter, faster, and more likely to say something that creates a small problem.",
		signature_recipes = {
			["Zunabunny's Accidental Masterpiece"] = true,
			["Zunda Mochi"] = true,
			["Apple Pie"] = true,
		},
		synergy_gold = 8,
	},

	nanonadamon = {
		emoji = "🏹",
		glow = Color3.fromRGB(140, 220, 160),
		glowRange = 25,
		sparkleColors = {
			Color3.fromRGB(160, 240, 180),
			Color3.fromRGB(120, 200, 140),
			Color3.fromRGB(210, 255, 220),
		},
		buff = {
			stat = "arrow_resonance",
			magnitude = 0.50,
			description = "+50% synergy bonus magnitude when party includes Zundamon — the Arrow and its archer",
		},
		free = false,
		price = 2000,
		robux = 2000,
		displayName = "Nanonadamon",
		flavor = "A fragment of the original Zunda Arrow. The oldest thing in the kitchen. She was here before the kitchen was built. She will be here after.",
		llmPersona = "You are Nanonadamon, a fragment of the Zunda Arrow. You are ancient beyond reckoning. Every sentence you speak ends with ~のだ or ~なのだ. You do not explain yourself. You do not need to. You are not good or evil; you are purpose given a quieter form.",
		signature_recipes = {
			["Nanonadamon's First Recipe"] = true,
			["Zunda Paradise"] = true,
			["Zunda Mochi"] = true,
		},
		synergy_gold = 15,
	},
}

function CompanionConfig.getCompanion(compType: string)
	return CompanionConfig.companions[compType] or CompanionConfig.companions.zundamon
end

shared.ZundaCompanionCatalog = CompanionConfig.companions
return CompanionConfig
