--!strict
-- [[ModuleScript] DamonTextureConfig]]
-- AUTO-GENERATED by scripts/emit_damon_texture_config.py
-- DO NOT HAND-EDIT. Re-run the script to regenerate.
--
-- Maps companion keys to their uploaded Roblox decal asset IDs.
-- An empty string means the texture has not been uploaded yet —
-- the UI falls back to the companion's glow color field.
--
-- Pipeline:
--   1. Generate:  python scripts/damon_texture_gen.py --all
--   2. Upload:    python scripts/damon_texture_upload.py --all
--   3. Emit:      python scripts/emit_damon_texture_config.py
--   See docs/TEXTURE_PIPELINE.md for the full guide.

local DamonTextureConfig = {}

DamonTextureConfig.textures = {
	ankomon = "",
	antimon = "",
	cardamon = "",
	cat = "",
	dog = "",
	hoshidamon = "",
	itakodamon = "",
	kagamon = "",
	karintomon = "",
	kinakomon = "",
	kiritandamon = "",
	kuroyurimon = "",
	matchamon = "",
	nanonadamon = "",
	parrot = "",
	sakuradamon = "",
	shisomon = "",
	sumimon = "",
	suzurimon = "",
	tantanmon = "",
	tsukimidamon = "",
	wasabimon = "",
	yurimon = "",
	zunabunny = "",
	zundamon = "",
	zunkodamon = "",
}

-- Returns the rbxassetid URI for a companion key, or "" if not uploaded yet.
function DamonTextureConfig.getTexture(key: string): string
	return DamonTextureConfig.textures[key] or ""
end

-- Returns true if a companion has an uploaded texture.
function DamonTextureConfig.hasTexture(key: string): boolean
	local t = DamonTextureConfig.textures[key]
	return t ~= nil and t ~= ""
end

return DamonTextureConfig
