-- [[ModuleScript] DecorationConfig (ref: RBX6F0E1238DEC14B5A8344D250D5F07D12)]]
-- DecorationConfig: Items players can place in their Garden or Cottage Plot
-- To add a new decoration: add an entry to garden_items or cottage_items.
-- Fields: id, name, price, description, modelName, zone ("garden"|"cottage"|"both")

local DecorationConfig = {}

-- ============================================================
-- GARDEN DECORATIONS
-- ============================================================
DecorationConfig.garden_items = {
	{
		id          = "pink_tulips",
		name        = "Pink Tulips",
		description = "A bunch of cheerful pink tulips!",
		modelName   = "PinkTulips",
		meshId      = "rbxassetid://130899236683010",
		price       = 15,
		tier        = 1,
		zone        = "garden",
		icon        = "🌷",
		buff        = { stat = "patience", magnitude = 0.05 },
	},
	{
		id          = "stone_lantern",
		name        = "Stone Lantern",
		description = "Light up the garden at night.",
		modelName   = "StoneLantern",
		meshId      = "rbxassetid://138139954211772",
		price       = 40,
		tier        = 1,
		zone        = "garden",
		icon        = "🏮",
		buff        = { stat = "xp", magnitude = 0.05 },
	},
	{
		id          = "garden_bench",
		name        = "Garden Bench",
		description = "A cozy wooden bench for relaxing.",
		modelName   = "GardenBench",
		meshId      = "rbxassetid://136635427702568",
		price       = 60,
		tier        = 1,
		zone        = "garden",
		icon        = "🪑",
		buff        = { stat = "gold", magnitude = 0.05 },
	},
	{
		id          = "fountain",
		name        = "Mini Fountain",
		description = "A decorative stone fountain with running water.",
		modelName   = "MiniFountain",
		meshId      = "rbxassetid://113416516962877",
		price       = 120,
		tier        = 2,
		zone        = "garden",
		icon        = "⛲",
		buff        = { stat = "gold", magnitude = 0.10 },
	},
	{
		id          = "cherry_tree",
		name        = "Cherry Blossom Tree",
		description = "A beautiful pink blossom tree!",
		modelName   = "CherryTree",
		meshId      = "rbxassetid://139609561607226",
		price       = 200,
		tier        = 2,
		zone        = "garden",
		icon        = "🌸",
		buff        = { stat = "patience", magnitude = 0.10 },
	},
}

-- ============================================================
-- COTTAGE / PLOT DECORATIONS
-- ============================================================
DecorationConfig.cottage_items = {
	{
		id          = "wooden_table",
		name        = "Wooden Table",
		description = "A simple wooden table for your cottage.",
		modelName   = "WoodenTable",
		meshId      = "rbxassetid://104840247636112",
		price       = 30,
		tier        = 1,
		zone        = "cottage",
		icon        = "🪑",
		buff        = { stat = "patience", magnitude = 0.05 },
	},
	{
		id          = "bookshelf",
		name        = "Bookshelf",
		description = "Fill it with your favourite recipes!",
		modelName   = "Bookshelf",
		meshId      = "rbxassetid://91207913245126",
		price       = 50,
		tier        = 1,
		zone        = "cottage",
		icon        = "📚",
		buff        = { stat = "xp", magnitude = 0.10 },
	},
	{
		id          = "window_box",
		name        = "Window Flower Box",
		description = "Attach pink flowers to your cottage windows.",
		modelName   = "WindowBox",
		meshId      = "rbxassetid://135102403023499",
		price       = 35,
		tier        = 1,
		zone        = "cottage",
		icon        = "🌺",
		buff        = { stat = "gold", magnitude = 0.05 },
	},
	{
		id          = "fireplace",
		name        = "Stone Fireplace",
		description = "Warm up your cottage with a crackling fire.",
		modelName   = "Fireplace",
		meshId      = "rbxassetid://134866502624356",
		price       = 150,
		tier        = 2,
		zone        = "cottage",
		icon        = "🔥",
		buff        = { stat = "gold", magnitude = 0.10 },
	},
	{
		id          = "fancy_bed",
		name        = "Fancy Bed",
		description = "Sleep in style after a long day serving guests!",
		modelName   = "FancyBed",
		meshId      = "rbxassetid://84413770753250",
		price       = 180,
		tier        = 2,
		zone        = "cottage",
		icon        = "🛏️",
		buff        = { stat = "xp", magnitude = 0.15 },
	},
	{
		id          = "trophy_shelf",
		name        = "Trophy Shelf",
		description = "Display your tier badges and achievements.",
		modelName   = "TrophyShelf",
		meshId      = "rbxassetid://85673361470819",
		price       = 250,
		tier        = 3,
		zone        = "cottage",
		icon        = "🏆",
		buff        = { stat = "patience", magnitude = 0.20 },
	},
	{
		id          = "mushroom_stools",
		name        = "Mushroom Stools",
		description = "Whimsical mushroom-shaped seating.",
		modelName   = "MushroomStools",
		meshId      = "rbxassetid://83074166298228",
		price       = 100,
		tier        = 3,
		zone        = "garden",
		icon        = "🍄",
		buff        = { stat = "patience", magnitude = 0.15 },
	},
	{
		id          = "hanging_lanterns",
		name        = "Hanging Lanterns",
		description = "Warm fairy lights strung across your garden.",
		modelName   = "HangingLanterns",
		meshId      = "rbxassetid://107827339899349",
		price       = 140,
		tier        = 3,
		zone        = "garden",
		icon        = "🏮",
		buff        = { stat = "xp", magnitude = 0.12 },
	},
	{
		id          = "herb_shelf",
		name        = "Herb Shelf",
		description = "A wall shelf of fragrant cooking herbs.",
		modelName   = "HerbShelf",
		meshId      = "rbxassetid://139370728430043",
		price       = 80,
		tier        = 2,
		zone        = "cottage",
		icon        = "🌿",
		buff        = { stat = "gold", magnitude = 0.08 },
	},
	{
		id          = "display_case",
		name        = "Display Case",
		description = "Showcase your finest Zunda dishes.",
		modelName   = "DisplayCase",
		meshId      = "rbxassetid://87880759510308",
		price       = 110,
		tier        = 2,
		zone        = "cottage",
		icon        = "🍽️",
		buff        = { stat = "patience", magnitude = 0.12 },
	},
	{
		id          = "moon_gazer",
		name        = "Moon Gazer",
		description = "A crescent moon sculpture that glows at night.",
		modelName   = "MoonGazer",
		meshId      = "rbxassetid://117498522944811",
		price       = 300,
		tier        = 4,
		zone        = "garden",
		icon        = "🌙",
		buff        = { stat = "xp", magnitude = 0.18 },
	},
	{
		id          = "grand_stove",
		name        = "Grand Stove",
		description = "A legendary stove for legendary dishes.",
		modelName   = "GrandStove",
		meshId      = "rbxassetid://78920643918582",
		price       = 400,
		tier        = 4,
		zone        = "cottage",
		icon        = "🔥",
		buff        = { stat = "gold", magnitude = 0.15 },
	},
	{
		id          = "spice_rack",
		name        = "Spice Rack Collection",
		description = "Every grand chef needs their spices displayed proudly.",
		modelName   = "SpiceRack",
		meshId      = "rbxassetid://87666986711975",
		price       = 220,
		tier        = 4,
		zone        = "cottage",
		icon        = "🌶️",
		buff        = { stat = "patience", magnitude = 0.18 },
	},
}

return DecorationConfig
