-- [[ModuleScript] QuestConfig (ref: RBXF6CB94E09956482FB9EF70B219DFF3C7)]]
-- QuestConfig: Data-driven quest definitions
-- Persisted by QuestManager; modified by admin menus

local QuestConfig = {
	quests = {
		-- Example quest structure:
		-- {
		--   id = "quest_1",
		--   name = "First Guests",
		--   description = "Serve 5 guests at the kitchen",
		--   icon = "🍽️",
		--   type = "serve", -- serve, cook, gather, earn_gold
		--   target = 5, -- guests to serve
		--   rewards = {
		--     gold = 50,
		--     tier_points = 10,
		--     items = {}
		--   },
		--   difficulty = 1 -- 1-5 scale
		-- }
	},

	-- Default quests to initialize on player join
	default_quests = {
		{
			id = "quest_welcome_1",
			name = "Welcome to the Kitchen",
			description = "Serve your first guest",
			icon = "🍽️",
			type = "serve",
			target = 1,
			rewards = {
				gold = 25,
				tier_points = 5,
				items = {},
			},
			difficulty = 1,
		},
		{
			id = "quest_cafe_master",
			name = "Café Master",
			description = "Serve 10 guests",
			icon = "⭐",
			type = "serve",
			target = 10,
			rewards = {
				gold = 100,
				tier_points = 20,
				items = {},
			},
			difficulty = 2,
		},
		-- NEW ZUNDA-THEMED QUESTS
		{
			id = "quest_zunda_pea_collector",
			name = "Zunda Pea Collector",
			description = "Gather 10 Zunda Peas from the garden",
			icon = "🌱",
			type = "gather",
			target = 10,
			target_item = "Zunda Pea",
			rewards = {
				gold = 50,
				tier_points = 10,
				items = { "Zunda Mochi" },
			},
			difficulty = 1,
		},
		{
			id = "quest_edamame_harvest",
			name = "Edamame Harvest",
			description = "Collect 5 Edamame Pods",
			icon = "🌿",
			type = "gather",
			target = 5,
			target_item = "Edamame Pod",
			rewards = {
				gold = 75,
				tier_points = 15,
				items = {},
			},
			difficulty = 2,
		},
		{
			id = "quest_zunda_mochi_master",
			name = "Zunda Mochi Master",
			description = "Craft 3 Zunda Mochi",
			icon = "🍡",
			type = "cook",
			target = 3,
			target_item = "Zunda Mochi",
			rewards = {
				gold = 150,
				tier_points = 30,
				items = { "Sweet Pea" },
			},
			difficulty = 3,
		},
		{
			id = "quest_pea_flower_garden",
			name = "Pea Flower Garden",
			description = "Find 8 Pea Flowers",
			icon = "🌸",
			type = "gather",
			target = 8,
			target_item = "Pea Flower",
			rewards = {
				gold = 100,
				tier_points = 20,
				items = {},
			},
			difficulty = 2,
		},
		{
			id = "quest_zunda_paradise",
			name = "Zunda Paradise Chef",
			description = "Cook the legendary Zunda Paradise dish",
			icon = "✨",
			type = "cook",
			target = 1,
			target_item = "Zunda Paradise",
			rewards = {
				gold = 500,
				tier_points = 100,
				items = {},
			},
			difficulty = 5,
		},
		{
			id = "quest_zundarooms_signal",
			name = "A Wall That Breathes",
			description = "Serve one guest and investigate the unstable wall near the village entrance",
			icon = "?",
			type = "serve",
			target = 1,
			rewards = { gold = 25, tier_points = 5, items = {} },
			difficulty = 1,
			subtext = "After your first happy guest leaves, a wall near the village entrance begins humming out of rhythm.",
			unlock_hint = "The Zundarooms can now be entered through an unstable wall.",
		},
		{
			id = "quest_zundarooms_escape",
			name = "The Rooms Without a Recipe",
			description = "Enter the Zundarooms and escape the unidentified entity",
			icon = "?",
			type = "zundarooms_escape",
			target = 1,
			rewards = { gold = 150, tier_points = 30, items = {} },
			difficulty = 3,
			subtext = "No map records this place. Follow the pale doorway and do not turn around.",
			unlock_hint = "A memory from the Zundarooms has appeared in your collection.",
		},

		-- ─────────────────────────────────────────────────────
		-- NEW QUEST BATCH — gathering, cooking, serving, exploration, mastery
		-- ─────────────────────────────────────────────────────

		-- GATHERING quests
		{
			id = "quest_apple_picker",
			name = "Apple Picker",
			description = "Pick 20 apples from the orchard",
			icon = "\u{1F34E}",
			type = "gather",
			target = 20,
			target_item = "Apple",
			rewards = { gold = 80, tier_points = 15, items = {} },
			difficulty = 1,
		},
		{
			id = "quest_wheat_field",
			name = "Wheat Field Worker",
			description = "Harvest 30 wheat",
			icon = "\u{1F33E}",
			type = "gather",
			target = 30,
			target_item = "Wheat",
			rewards = { gold = 60, tier_points = 12, items = {} },
			difficulty = 1,
		},
		{
			id = "quest_sweet_pea_search",
			name = "Sweet Pea Search",
			description = "Find 12 Sweet Peas in the garden",
			icon = "\u{1FAD8}",
			type = "gather",
			target = 12,
			target_item = "Sweet Pea",
			rewards = { gold = 120, tier_points = 20, items = {} },
			difficulty = 2,
		},
		{
			id = "quest_zunda_leaf_walk",
			name = "Leafy Walk",
			description = "Collect 15 Zunda Leaves",
			icon = "\u{1F343}",
			type = "gather",
			target = 15,
			target_item = "Zunda Leaf",
			rewards = { gold = 90, tier_points = 18, items = {} },
			difficulty = 2,
		},
		{
			id = "quest_gold_prospector",
			name = "Gold Prospector",
			description = "Mine 5 nuggets of Gold from the rocks",
			icon = "\u{1F4B0}",
			type = "gather",
			target = 5,
			target_item = "Gold",
			rewards = { gold = 200, tier_points = 30, items = {} },
			difficulty = 3,
		},

		-- COOKING quests
		{
			id = "quest_bread_baker",
			name = "Bread Baker",
			description = "Bake 5 loaves of Bread",
			icon = "\u{1F35E}",
			type = "cook",
			target = 5,
			target_item = "Bread",
			rewards = { gold = 100, tier_points = 18, items = {} },
			difficulty = 1,
		},
		{
			id = "quest_apple_pie_party",
			name = "Apple Pie Party",
			description = "Cook 4 Apple Pies",
			icon = "\u{1F967}",
			type = "cook",
			target = 4,
			target_item = "Apple Pie",
			rewards = { gold = 160, tier_points = 24, items = {} },
			difficulty = 2,
		},
		{
			id = "quest_pea_flower_tea",
			name = "Tea Time",
			description = "Brew 3 cups of Pea Flower Tea",
			icon = "\u{1F375}",
			type = "cook",
			target = 3,
			target_item = "Pea Flower Tea",
			rewards = { gold = 180, tier_points = 28, items = {} },
			difficulty = 2,
		},
		{
			id = "quest_royal_stew",
			name = "Royal Cuisine",
			description = "Prepare 2 servings of Royal Stew",
			icon = "\u{1F35B}",
			type = "cook",
			target = 2,
			target_item = "Royal Stew",
			rewards = { gold = 240, tier_points = 35, items = {} },
			difficulty = 3,
		},
		{
			id = "quest_perfect_cook_streak",
			name = "Perfect Cook Streak",
			description = "Land 5 PERFECT timing cooks",
			icon = "\u{2728}",
			type = "cook_perfect",
			target = 5,
			rewards = { gold = 300, tier_points = 45, items = {} },
			difficulty = 3,
		},

		-- SERVING / GUEST quests
		{
			id = "quest_breakfast_rush",
			name = "Breakfast Rush",
			description = "Serve 3 guests before noon",
			icon = "\u{1F373}",
			type = "serve",
			target = 3,
			rewards = { gold = 90, tier_points = 18, items = {} },
			difficulty = 1,
		},
		{
			id = "quest_dinner_rush",
			name = "Dinner Rush",
			description = "Serve 15 guests in a day",
			icon = "\u{1F37D}",
			type = "serve",
			target = 15,
			rewards = { gold = 220, tier_points = 32, items = {} },
			difficulty = 3,
		},
		{
			id = "quest_legendary_host",
			name = "Legendary Host",
			description = "Serve 50 guests total",
			icon = "\u{1F451}",
			type = "serve",
			target = 50,
			rewards = { gold = 500, tier_points = 80, items = {} },
			difficulty = 4,
		},

		-- ECONOMY quests
		{
			id = "quest_first_100_gold",
			name = "First Coins",
			description = "Earn 100 gold total",
			icon = "\u{1FA99}",
			type = "earn_gold",
			target = 100,
			rewards = { gold = 25, tier_points = 8, items = {} },
			difficulty = 1,
		},
		{
			id = "quest_gold_hoard",
			name = "Gold Hoard",
			description = "Accumulate 1,000 gold",
			icon = "\u{1F4B0}",
			type = "earn_gold",
			target = 1000,
			rewards = { gold = 150, tier_points = 35, items = {} },
			difficulty = 3,
		},
		{
			id = "quest_master_economist",
			name = "Master Economist",
			description = "Accumulate 5,000 gold",
			icon = "\u{1F4B5}",
			type = "earn_gold",
			target = 5000,
			rewards = { gold = 500, tier_points = 80, items = {} },
			difficulty = 5,
		},

		-- EXPLORATION quests (uses zone visit / building entry)
		{
			id = "quest_visit_kitchen",
			name = "Find the Kitchen",
			description = "Visit the Kitchen Workshop",
			icon = "\u{1F373}",
			type = "visit_zone",
			target = 1,
			target_zone = "Kitchen",
			rewards = { gold = 30, tier_points = 5, items = {} },
			difficulty = 1,
		},
		{
			id = "quest_visit_pagoda",
			name = "Peaceful Pilgrimage",
			description = "Visit the Pagoda in the Zen Garden",
			icon = "\u{26E9}",
			type = "visit_zone",
			target = 1,
			target_zone = "Pagoda",
			rewards = { gold = 60, tier_points = 10, items = {} },
			difficulty = 1,
		},
		{
			id = "quest_visit_ruins",
			name = "Ancient Whispers",
			description = "Discover the Ancient Ruins",
			icon = "\u{1F3DB}",
			type = "visit_zone",
			target = 1,
			target_zone = "AncientRuins",
			rewards = { gold = 100, tier_points = 18, items = {} },
			difficulty = 2,
		},
		{
			id = "quest_visit_all_zones",
			name = "World Tour",
			description = "Visit every zone at least once",
			icon = "\u{1F30D}",
			type = "visit_zones_unique",
			target = 5,
			rewards = { gold = 350, tier_points = 55, items = {} },
			difficulty = 3,
		},

		-- COMPANION / SOCIAL quests
		{
			id = "quest_chat_with_zundapal",
			name = "Best Friends",
			description = "Chat with Zundamon 5 times",
			icon = "\u{1F361}",
			type = "companion_chat",
			target = 5,
			rewards = { gold = 50, tier_points = 12, items = {} },
			difficulty = 1,
		},
		{
			id = "quest_meet_elder",
			name = "Wisdom of the Elder",
			description = "Speak with the Village Elder",
			icon = "\u{1F3EE}",
			type = "npc_chat",
			target = 1,
			target_npc = "Elder",
			rewards = { gold = 75, tier_points = 14, items = {} },
			difficulty = 2,
		},

		-- MASTERY quests (long-running)
		{
			id = "quest_recipe_collector",
			name = "Recipe Collector",
			description = "Cook every recipe at least once",
			icon = "📖",
			type = "cook_unique",
			target = 12,
			rewards = { gold = 600, tier_points = 90, items = {} },
			difficulty = 4,
			subtext = "The Chef's Testament demands every dish be tasted. You've mastered the basics — now hunt down every recipe in existence. Each one tells a story. Each one earns a star.",
			npc_dialogue = {
				speaker = "chef",
				lines = { "You think you know cooking? HA. Cook EVERYTHING. Then come back and I MIGHT be impressed." },
			},
		},
		{
			id = "quest_zunda_grand_master",
			name = "Zunda Grand Master",
			description = "Cook every Zunda-themed recipe",
			icon = "🥞",
			type = "cook_unique_zunda",
			target = 6,
			rewards = { gold = 700, tier_points = 120, items = {} },
			difficulty = 5,
			subtext = "The Zunda spirits have been watching. Every pea you've mashed, every mochi you've pounded — it all leads here. Cook every Zunda dish and claim the title of GRAND MASTER.",
			npc_dialogue = {
				speaker = "zundamon",
				lines = {
					"YOU'RE SO CLOSE I CAN TASTE IT!!! Literally. I ate a pea. But STILL. COOK ALL THE THINGS 🍡🔥",
					"ZUNDA PARADISE is the final test. 15 Zunda Peas!!! 10 Edamame!!! 5 Sweet Peas!!! 3 Pea Flowers!!! GO!!! GO!!! GO!!!",
				},
			},
			chain_id = "zunda_legend",
			chain_step = 3,
		},

		-- ════════════════════════════════════════════════════════════════
		-- NEW QUEST BATCH v2 — Chains, subtext, companion & seasonal
		-- ════════════════════════════════════════════════════════════════

		-- ── CHAIN: "The Great Zunda Hunt" (gathering) ──────────────────
		{
			id = "quest_zunda_hunt_1",
			name = "Zunda Pea Hunting",
			description = "Gather 15 Zunda Peas",
			icon = "🌱",
			type = "gather",
			target = 15,
			target_item = "Zunda Pea",
			rewards = { gold = 80, tier_points = 15, items = {} },
			difficulty = 2,
			subtext = "The village elder says the first Zunda Peas were discovered by a chef who chased a rainbow into a field. 'Follow the glint,' he said. 'Stampede the peas.' Now it's your turn.",
			chain_id = "great_zunda_hunt",
			chain_step = 1,
		},
		{
			id = "quest_zunda_hunt_2",
			name = "Edamame Expedition",
			description = "Collect 10 Edamame Pods",
			icon = "🌿",
			type = "gather",
			target = 10,
			target_item = "Edamame Pod",
			rewards = { gold = 120, tier_points = 20, items = { "Sweet Pea" } },
			difficulty = 2,
			subtext = "Deep in the Edamame Thicket, the pods hang like green lanterns. Legend says they only reveal themselves to those who approach with a full belly and an empty mind. Also, you need 10 of them.",
			chain_id = "great_zunda_hunt",
			chain_step = 2,
		},
		{
			id = "quest_zunda_hunt_3",
			name = "Pea Flower Pilgrimage",
			description = "Find 12 Pea Flowers",
			icon = "🌸",
			type = "gather",
			target = 12,
			target_item = "Pea Flower",
			rewards = { gold = 160, tier_points = 28, items = { "Pea Flower Tea" } },
			difficulty = 3,
			subtext = "The Pea Flowers bloom only where a Zunda chef once wept tears of joy. Follow the scent of crushed petals and distant happiness. Each flower you pick whispers a recipe from the Old Kitchen.",
			npc_dialogue = {
				speaker = "elder",
				lines = {
					"Ah, the Pea Flower Pilgrimage... I remember my first bloom. The flowers sing, you know. Not with words — with FLAVOR. Collect 12 and the path forward will reveal itself.",
				},
			},
			chain_id = "great_zunda_hunt",
			chain_step = 3,
		},
		{
			id = "quest_zunda_hunt_4",
			name = "The Great Zunda Hunt",
			description = "Gather every Zunda ingredient at least once",
			icon = "🏆",
			type = "gather_unique",
			target = 9,
			rewards = { gold = 400, tier_points = 60, items = { "Zunda Paradise" } },
			difficulty = 4,
			subtext = "You've tasted the first fruits. NOW COMES THE HUNT. Zunda Pea. Edamame Pod. Sweet Pea. Pea Flower. Zunda Flower. Zunda Berry. Zunda Mushroom. Zunda Root. Zunda Leaf. COLLECT THEM ALL. The Zunda spirits demand tribute.",
			npc_dialogue = {
				speaker = "zundamon",
				lines = {
					"THE GREAT HUNT!!! I'M SHAKING!!! 🌱✨",
					"Every Zunda ingredient has a spirit inside. If you gather ALL 9 types, they'll COMBINE into something LEGENDARY. I'M NOT KIDDING. I SAW IT IN A DREAM. 🔥🔥🔥",
				},
			},
			chain_id = "great_zunda_hunt",
			chain_step = 4,
		},

		-- ── CHAIN: "Culinary Ascension" (cooking) ─────────────────────
		{
			id = "quest_culinary_1",
			name = "First Loaf",
			description = "Bake 3 loaves of Bread",
			icon = "🍞",
			type = "cook",
			target = 3,
			target_item = "Bread",
			rewards = { gold = 40, tier_points = 10, items = {} },
			difficulty = 1,
			subtext = "Every master chef started with bread. The Zunda monks believed the first loaf teaches patience, heat control, and the importance of NOT setting the kitchen on fire. Three loaves. Simple. Pure. Begin.",
			chain_id = "culinary_ascension",
			chain_step = 1,
		},
		{
			id = "quest_culinary_2",
			name = "Pie Prodigy",
			description = "Bake 3 Apple Pies with great timing",
			icon = "🥧",
			type = "cook_quality",
			target = 3,
			target_item = "Apple Pie",
			quality = "great",
			rewards = { gold = 120, tier_points = 22, items = {} },
			difficulty = 2,
			subtext = "A good pie is edible. A GREAT pie is a STATEMENT. The Zunda elders say the perfect Apple Pie crust should be 'golden as sunrise, flaky as autumn leaves, and warm as a hug after a long day.' Three pies. Make them proud.",
			chain_id = "culinary_ascension",
			chain_step = 2,
		},
		{
			id = "quest_culinary_3",
			name = "Royal Preparation",
			description = "Cook Royal Stew twice",
			icon = "👑",
			type = "cook",
			target = 2,
			target_item = "Royal Stew",
			rewards = { gold = 200, tier_points = 30, items = {} },
			difficulty = 3,
			subtext = "Royal Stew is not a meal — it's a coronation. The recipe was passed down by the Zunda King himself, who insisted on GOLD in his stew because 'commoners eat from bowls. KINGS EAT FROM BOWLS OF WEALTH.' Two servings. Rule the kitchen.",
			npc_dialogue = {
				speaker = "chef",
				lines = {
					"Royal Stew, huh? Bold choice. Most beginners CRUMBLE under the pressure of cooking with actual GOLD ORE.",
					"But you... you have the Zunda glint in your eye. COOK IT. TASTE IT. BECOME IT.",
				},
			},
			chain_id = "culinary_ascension",
			chain_step = 3,
		},
		{
			id = "quest_culinary_4",
			name = "Feast of Legends",
			description = "Cook 1 Ultimate Feast",
			icon = "🏛️",
			type = "cook",
			target = 1,
			target_item = "Ultimate Feast",
			rewards = { gold = 500, tier_points = 80, items = {} },
			difficulty = 4,
			subtext = "The Ultimate Feast is not on any menu. It IS the menu. The Zunda monks cooked it only during celestial alignments. 30 Wheat. 20 Apples. 5 Gold. This dish doesn't feed people — it INAUGURATES them. Cook it once. Be forever changed.",
			npc_dialogue = {
				speaker = "narrator",
				lines = {
					"[ The kitchen grows dark. The stove flickers. Somewhere, a pea rolls across the floor. ]",
					"[ A voice from the flames whispers: 'You dare to cook the FEAST?' ]",
				},
			},
			chain_id = "culinary_ascension",
			chain_step = 4,
		},
		{
			id = "quest_culinary_5",
			name = "Culinary Ascension",
			description = "Achieve a 10-cook perfect streak",
			icon = "🌟",
			type = "cook_perfect",
			target = 10,
			rewards = { gold = 800, tier_points = 120, items = { "Zundamon's Banquet" } },
			difficulty = 5,
			subtext = "The final trial. 10 PERFECT cooks in a row. No burnt edges. No undercooked centers. Just FLAWLESS CULINARY DOMINATION. The Zunda spirits will witness. The kitchen will SHAKE. AND YOU WILL RISE.",
			npc_dialogue = {
				speaker = "zundamon",
				lines = {
					"10 PERFECT COOKS!!! DO YOU HAVE ANY IDEA WHAT THAT MEANS?!?! 🔥🔥🔥",
					"THE KITCHEN ITSELF WILL RECOGNIZE YOU!!! THE STOVE WILL BOW!!! THE SPATULAS WILL SALUTE!!! GO GO GO!!!",
				},
			},
			chain_id = "culinary_ascension",
			chain_step = 5,
		},

		-- ── CHAIN: "Seasons of Flavor" (seasonal dishes) ──────────────
		{
			id = "quest_seasonal_summer",
			name = "Summer Breeze",
			description = "Cook 2 Seasonal Salads",
			icon = "☀️",
			type = "cook",
			target = 2,
			target_item = "Seasonal Salad",
			rewards = { gold = 130, tier_points = 22, items = { "Zunda Berry" } },
			difficulty = 2,
			subtext = "Summer in Zunda Village is a riot of color. The Zunda Berries are at their plumpest, the leaves are crisp, and the air smells of sunshine. The Seasonal Salad captures all of it in a bowl. Taste the sun.",
			npc_dialogue = {
				speaker = "sakuradamon",
				lines = {
					"🌸 SUMMER IS HERE AND THE BERRIES ARE SCREAMING TO BE PICKED!!!",
					"The Seasonal Salad is a celebration of light itself!!! 3 Zunda Berries + 2 Zunda Leaves = PERFECTION IN A BOWL!!!",
				},
			},
			chain_id = "seasons_of_flavor",
			chain_step = 1,
		},
		{
			id = "quest_seasonal_winter",
			name = "Winter Warmth",
			description = "Cook 2 Warm Winter Stews",
			icon = "❄️",
			type = "cook",
			target = 2,
			target_item = "Warm Winter Stew",
			rewards = { gold = 200, tier_points = 32, items = {} },
			difficulty = 3,
			subtext = "When snow blankets Zunda Village, the only cure is the Warm Winter Stew. Zunda Roots roasted for hours, Zunda Mushrooms simmered in gold-infused broth. One spoonful and you'll forget the cold exists. 'A hug in a bowl,' the elders call it.",
			npc_dialogue = {
				speaker = "elder",
				lines = {
					"The cold bites hard this season. But the stew... the stew bites BACK. ❄️🔥",
					"Zunda Roots from the permafrost. Zunda Mushrooms from the snow-kissed logs. And a pinch of gold because you're WORTH IT.",
				},
			},
			chain_id = "seasons_of_flavor",
			chain_step = 2,
		},
		{
			id = "quest_seasonal_master",
			name = "Four Seasons Chef",
			description = "Cook every seasonal dish",
			icon = "🌍",
			type = "cook_unique_seasonal",
			target = 2,
			rewards = { gold = 350, tier_points = 50, items = { "Golden Harvest Platter" } },
			difficulty = 3,
			subtext = "Spring peas, summer berries, autumn roots, winter mushrooms. You've tasted each season. Now prove you can command them all. Cook every seasonal dish and become the Four Seasons Chef of Zunda Village.",
			chain_id = "seasons_of_flavor",
			chain_step = 3,
		},

		-- ── CHAIN: "Friend of All" (companion) ────────────────────────
		{
			id = "quest_friend_chat",
			name = "Hello Friend",
			description = "Chat with your companion 10 times",
			icon = "💬",
			type = "companion_chat",
			target = 10,
			rewards = { gold = 60, tier_points = 15, items = {} },
			difficulty = 1,
			subtext = "Your companion is more than a follower — they're your kitchen soulmate. Every chat deepens your bond. Who knows what secrets they'll share after 10 heart-to-hearts?",
			chain_id = "friend_of_all",
			chain_step = 1,
		},
		{
			id = "quest_friend_elder",
			name = "Elder's Wisdom",
			description = "Speak with the Village Elder 3 times",
			icon = "🏮",
			type = "npc_chat",
			target = 3,
			target_npc = "Elder",
			rewards = { gold = 100, tier_points = 18, items = {} },
			difficulty = 2,
			subtext = "The Village Elder has seen empires rise and fall on the strength of their stews. He carries the Old Knowledge. Three conversations might earn you a secret even the Zunda monks forgot.",
			npc_dialogue = {
				speaker = "elder",
				lines = {
					"You keep coming back. Good. Most lack the patience for an old man's rambling.",
					"But YOU... you have the Zunda hunger. Come, sit. I'll tell you about the GOLDEN PEA OF LEGEND... but only after three visits.",
				},
			},
			chain_id = "friend_of_all",
			chain_step = 2,
		},
		{
			id = "quest_friend_all",
			name = "Friend of All",
			description = "Chat with every NPC in the village",
			icon = "🤝",
			type = "npc_chat_all",
			target = 5,
			rewards = { gold = 250, tier_points = 40, items = { "Antimon's Speed Soup" } },
			difficulty = 3,
			subtext = "Zunda Village is held together by its characters. The Chef. The Elder. The Whisper in the Ruins. Make yourself known to every soul who calls this place home. A kitchen is nothing without its community.",
			chain_id = "friend_of_all",
			chain_step = 3,
		},

		-- ── COMPANION-SPECIFIC QUESTS ─────────────────────────────────
		{
			id = "quest_ankomon_strength",
			name = "Ankomon's Trial of Protein",
			description = "Cook Ankomon's Protein Punch 3 times",
			icon = "💪",
			type = "cook",
			target = 3,
			target_item = "Ankomon's Protein Punch",
			rewards = { gold = 250, tier_points = 35, items = {} },
			difficulty = 3,
			subtext = "Ankomon challenges you to a test of PURE PROTEIN POWER. 'Each punch,' he says, 'is 5 Edamame Pods + 3 Zunda Peas + 1 Gold of pure RESPECT.' Cook it thrice. Prove your BEAN WORTHY.",
			npc_dialogue = {
				speaker = "ankomon",
				lines = {
					"🥜🥊 PROTEIN PUNCH!!! THIS ISN'T JUST FOOD IT'S A WORKOUT!!!",
					"COOK IT THREE TIMES AND I'LL ADMIT YOU HAVE BEAN SPIRIT!!! FAIL AND YOU'RE ON SOUP DUTY FOR A WEEK!!!",
				},
			},
		},
		{
			id = "quest_cardamon_zen",
			name = "Cardamon's Path of Patience",
			description = "Cook 5 dishes with GREAT quality or better",
			icon = "🧘",
			type = "cook_quality",
			target = 5,
			quality = "great",
			rewards = { gold = 200, tier_points = 30, items = { "Cardamon's Calm Cup" } },
			difficulty = 2,
			subtext = "Cardamon whispers: 'Speed means nothing. PRESENCE means everything.' Five dishes, each made with mindfulness and intent. Not rushed. Not forced. JUST. GREAT. Breathe in. Cook out.",
			npc_dialogue = {
				speaker = "cardamon",
				lines = {
					"🌿🍋 Patience... breathe... C O O K...",
					"Five great dishes. Not 'good'. GREAT. I'll know the difference. YOUR SOUL WILL KNOW THE DIFFERENCE.",
				},
			},
		},
		{
			id = "quest_antimon_speed",
			name = "Antimon's Speed Trial",
			description = "Cook 3 dishes under 4 seconds each",
			icon = "⚡",
			type = "cook_speed",
			target = 3,
			max_cook_time = 4,
			rewards = { gold = 180, tier_points = 28, items = { "Antimon's Speed Soup" } },
			difficulty = 2,
			subtext = "Antimon vibrates with impatience. 'THE TIMING BAR IS NOT A SUGGESTION!!!' Three dishes. Under 4 seconds each. NO MISTAKES. SPEED IS FLAVOR. CHAOS IS TECHNIQUE.",
			npc_dialogue = {
				speaker = "antimon",
				lines = {
					"⚡💨 SPEED SPEED SPEED!!! THE TIMER IS YOUR BEST FRIEND AND WORST ENEMY!!!",
					"COOK LIKE THE WIND!!! 4 SECONDS!!! MAXIMUM!!!",
				},
			},
		},
		{
			id = "quest_sakuradamon_bloom",
			name = "Sakuradamon's Blossom Festival",
			description = "Cook 3 Sakuradamon's Blossom Bites",
			icon = "🌸",
			type = "cook",
			target = 3,
			target_item = "Sakuradamon's Blossom Bites",
			rewards = { gold = 280, tier_points = 38, items = {} },
			difficulty = 3,
			subtext = "Sakuradamon's petals glow brighter when her favorite dish is made. 'Blossom Bites,' she says, 'are not cooked — they're BLOOMED.' 4 Pea Flowers + 3 Zunda Berries. Each one a celebration of impermanent beauty.",
			npc_dialogue = {
				speaker = "sakuradamon",
				lines = {
					"🌸💥 THE BLOSSOMS ARE ALIGNED!!! IT'S FESTIVAL TIME!!!",
					"Each Blossom Bite captures a moment of pure spring joy. COOK THREE. LET THE PETALS FALL WHERE THEY MAY.",
				},
			},
		},

		-- ── EXPLORATION QUESTS v2 ────────────────────────────────────
		{
			id = "quest_explore_garden",
			name = "Garden Secrets",
			description = "Find the hidden garden alcove",
			icon = "🌳",
			type = "visit_zone",
			target = 1,
			target_zone = "GardenAlcove",
			rewards = { gold = 70, tier_points = 14, items = {} },
			difficulty = 1,
			subtext = "Behind the old bakery, past the overgrown trellis, there's a hidden alcove where the first Zunda Peas were cultivated. The soil there still hums with ancient pea energy. FIND IT.",
		},
		{
			id = "quest_explore_well",
			name = "Well of Whispers",
			description = "Discover the Old Well",
			icon = "🧺",
			type = "visit_zone",
			target = 1,
			target_zone = "OldWell",
			rewards = { gold = 90, tier_points = 16, items = { "Zunda Root" } },
			difficulty = 2,
			subtext = "The Old Well at the village edge is more than it seems. Locals say if you drop a Zunda Pea in and listen carefully, you can hear the recipes of chefs long past. The well KNOWS things.",
			npc_dialogue = {
				speaker = "elder",
				lines = {
					"The Old Well... be careful near it. Some say it's bottomless. Some say it leads to THE KITCHEN BELOW.",
					"But if you listen close at midnight, you might hear the sound of perfect timing. Tick. Tock. COOK.",
				},
			},
		},
		{
			id = "quest_explore_waterfall",
			name = "Cascade Kitchen",
			description = "Find the hidden waterfall cave",
			icon = "🌊",
			type = "visit_zone",
			target = 1,
			target_zone = "WaterfallCave",
			rewards = { gold = 140, tier_points = 22, items = { "Zunda Mushroom" } },
			difficulty = 2,
			subtext = "Behind the Great Waterfall lies a cave where Zunda monks aged their finest stews. The humidity. The cool air. The MUSHROOMS that glow in the dark. Some say the cave still holds a vat of 100-year-old stew...",
		},
		{
			id = "quest_explore_all",
			name = "Cartographer of Flavor",
			description = "Discover 10 unique locations",
			icon = "🗺️",
			type = "visit_zones_unique",
			target = 10,
			rewards = { gold = 500, tier_points = 75, items = { "Golden Harvest Platter" } },
			difficulty = 4,
			subtext = "Zunda Village is vast, and every corner hides a culinary secret. 10 locations. 10 stories. 10 chances to find ingredients no one else has touched. Become the Cartographer of Flavor. Map the delicious unknown.",
			npc_dialogue = {
				speaker = "narrator",
				lines = {
					"[ A scroll unfurls across the map table, revealing uncharted territories... ]",
					"[ Ink swirls into shapes: 'Here be ZUNDA PEAS.' The map is hungry for discovery. ]",
				},
			},
		},

		-- ── ECONOMY / GOLD QUESTS v2 ────────────────────────────────
		{
			id = "quest_gold_rush_1",
			name = "Pocket Change",
			description = "Earn 250 gold total",
			icon = "💰",
			type = "earn_gold",
			target = 250,
			rewards = { gold = 30, tier_points = 10, items = {} },
			difficulty = 1,
			subtext = "Every gold coin starts with a single dish served. 250 gold might sound like pocket change to a Zunda veteran, but to a BEGINNER CHEF? It's the first step toward culinary empire.",
			chain_id = "gold_rush",
			chain_step = 1,
		},
		{
			id = "quest_gold_rush_2",
			name = "Gold Entree",
			description = "Accumulate 2,500 gold",
			icon = "💰",
			type = "earn_gold",
			target = 2500,
			rewards = { gold = 150, tier_points = 35, items = {} },
			difficulty = 3,
			subtext = "2500 gold. That's not pocket change anymore — that's a STEW FUND. The Zunda merchants start taking you seriously at this threshold. They might even show you the SECRET menu.",
			chain_id = "gold_rush",
			chain_step = 2,
		},
		{
			id = "quest_gold_rush_3",
			name = "Gold Rush Baron",
			description = "Accumulate 10,000 gold",
			icon = "💎",
			type = "earn_gold",
			target = 10000,
			rewards = { gold = 500, tier_points = 100, items = { "Ultimate Feast" } },
			difficulty = 5,
			subtext = "TEN THOUSAND GOLD. The stuff of Zunda LEGEND. Only the greatest chefs in Zunda Village history have reached this milestone. Your name will be carved into the Golden Spatula of Fame. FOREVER.",
			npc_dialogue = {
				speaker = "chef",
				lines = {
					"10,000 GOLD?!?!? I'VE BEEN COOKING FOR 40 YEARS AND I HAVEN'T REACHED THAT!!!",
					"...Who ARE you?!?! Are you THE CHOSEN ONE?!?! The Golden Pea Prophecy... it's REAL?!?!",
				},
			},
			chain_id = "gold_rush",
			chain_step = 3,
		},

		-- ── NEW COMPANION DISCOVERY QUESTS ────────────────────────────
		{
			id = "quest_meet_ankomon",
			name = "The Bean Awakening",
			description = "Summon Ankomon as your companion",
			icon = "🥜",
			type = "set_companion",
			target = 1,
			target_companion = "ankomon",
			rewards = { gold = 100, tier_points = 20, items = {} },
			difficulty = 2,
			subtext = "A red bean spirit stirs in the pantry. Ankomon doesn't follow just ANYONE — he follows those who RESPECT THE BEAN. Set him as your companion and feel the PROTEIN POWER course through your kitchen.",
		},
		{
			id = "quest_meet_cardamon",
			name = "The Calm Before the Cook",
			description = "Summon Cardamon as your companion",
			icon = "🍋",
			type = "set_companion",
			target = 1,
			target_companion = "cardamon",
			rewards = { gold = 100, tier_points = 20, items = {} },
			difficulty = 2,
			subtext = "A cardamom seedling spirit drifts through the herb garden. Cardamon brings PEACE to your kitchen. Set her as your companion and feel your perfect cooking window EXPAND.",
		},
		{
			id = "quest_meet_antimon",
			name = "The Speed Force",
			description = "Summon Antimon as your companion",
			icon = "🌿",
			type = "set_companion",
			target = 1,
			target_companion = "antimon",
			rewards = { gold = 100, tier_points = 20, items = {} },
			difficulty = 2,
			subtext = "A minty wisp zips past your stove. Antimon is PURE VELOCITY. Set him as your companion and unlock EXTRA DROPS from every gather. The kitchen will feel SLOW compared to him.",
		},
		{
			id = "quest_meet_sakuradamon",
			name = "Cherry Blossom Spirit",
			description = "Summon Sakuradamon as your companion",
			icon = "🌸",
			type = "set_companion",
			target = 1,
			target_companion = "sakuradamon",
			rewards = { gold = 100, tier_points = 20, items = {} },
			difficulty = 2,
			subtext = "Petals dance on the wind — Sakuradamon approaches. The blossom spirit carries knowledge of the old ways. Set her as your companion and gain +25% XP from everything you cook and serve.",
		},

		-- ════════════════════════════════════════════════════════
		-- 12 NOVEL -DAMON COMPANION 3-STAGE QUESTLINES (36 QUESTS)
		-- ════════════════════════════════════════════════════════

		-- ── 1. SUMIMON QUESTLINE ──────────────────────────────────
		{
			id = "quest_sumimon_1",
			name = "The Ink Scholar's Trail",
			description = "Gather 6 Zunda Mushrooms from the shaded woods",
			icon = "🖌️",
			type = "gather",
			target = 6,
			target_item = "Zunda Mushroom",
			rewards = { gold = 80, tier_points = 15, items = { "Zunda Leaf" } },
			difficulty = 2,
			subtext = "A dark mist swirls near the stone lanterns. Sumimon the ink scholar lingers in the damp shadows, observing the wild mushrooms.",
		},
		{
			id = "quest_sumimon_2",
			name = "Calligraphy on the Board",
			description = "Achieve 3 Perfect cooks to prove your brushstroke precision",
			icon = "📜",
			type = "cook_perfect",
			target = 3,
			rewards = { gold = 150, tier_points = 30, items = { "Sumimon's Ink-Wash Soba" }, bond_tier = 2 },
			difficulty = 3,
			subtext = "Sumimon watches your knife movements with keen eyes. Each slice must be as decisive as an ink stroke on white silk.",
		},
		{
			id = "quest_sumimon_3",
			name = "Immortal Brushwork",
			description = "Cook Sumimon's Ink-Wash Soba and serve 5 guests",
			icon = "🖌️",
			type = "serve",
			target = 5,
			rewards = { gold = 300, tier_points = 60, items = { "Sumimon's Ink-Wash Soba" } },
			difficulty = 4,
			companion_unlock = "sumimon",
			subtext = "The ink scholar bows deeply. Your cooking has given his melancholy soul a timeless purpose. Sumimon joins your journey!",
		},

		-- ── 2. KAGAMON QUESTLINE ──────────────────────────────────
		{
			id = "quest_kagamon_1",
			name = "A Glint in the Ruins",
			description = "Gather 4 Sweet Peas from the meadow edge",
			icon = "🪞",
			type = "gather",
			target = 4,
			target_item = "Sweet Pea",
			rewards = { gold = 80, tier_points = 15, items = { "Sweet Pea" } },
			difficulty = 2,
			subtext = "A dazzling sparkle catches your eye amid scorched stone. Kagamon strikes an idol pose, pretending the ancient burn marks are just stage lights.",
		},
		{
			id = "quest_kagamon_2",
			name = "Mirror, Mirror on the Plate",
			description = "Achieve 3 Great or Perfect cooks to dazzle the audience",
			icon = "✨",
			type = "cook_great",
			target = 3,
			rewards = { gold = 150, tier_points = 30, items = { "Kagamon's Glazed Mirror Mochi" }, bond_tier = 2 },
			difficulty = 3,
			subtext = "Kagamon beams with dazzling energy, cheering on every plate with breathless idol enthusiasm to hide her trembling glass.",
		},
		{
			id = "quest_kagamon_3",
			name = "Unbroken Radiance",
			description = "Cook Kagamon's Glazed Mirror Mochi and serve 5 guests",
			icon = "🪞",
			type = "serve",
			target = 5,
			rewards = { gold = 300, tier_points = 60, items = { "Kagamon's Glazed Mirror Mochi" } },
			difficulty = 4,
			companion_unlock = "kagamon",
			subtext = "You see the fine hairline fractures in her mirror and praise her anyway. Kagamon sheds happy tears and pledges to shine by your side!",
		},

		-- ── 3. SUZURIMON QUESTLINE ────────────────────────────────
		{
			id = "quest_suzurimon_1",
			name = "The Drowned Bell's Chime",
			description = "Gather 5 Pea Flowers near the riverside garden",
			icon = "🔔",
			type = "gather",
			target = 5,
			target_item = "Pea Flower",
			rewards = { gold = 80, tier_points = 15, items = { "Pea Flower" } },
			difficulty = 2,
			subtext = "A solemn bronze chime rings from the misty riverbank. Suzurimon stands vigil where ancient floods once washed away a mountain shrine.",
		},
		{
			id = "quest_suzurimon_2",
			name = "Rhythm of the Bronze Guardian",
			description = "Complete 4 Perfect cooks to align with the sacred bell tempo",
			icon = "⏱️",
			type = "cook_perfect",
			target = 4,
			rewards = { gold = 150, tier_points = 30, items = { "Suzurimon's Bell Chime Dango" }, bond_tier = 2 },
			difficulty = 3,
			subtext = "The sacred bell tolls in harmony with your cooking. Suzurimon nods stoically as your rhythm holds unbroken.",
		},
		{
			id = "quest_suzurimon_3",
			name = "Sacred Resonance",
			description = "Cook Suzurimon's Bell Chime Dango and serve 6 guests",
			icon = "🔔",
			type = "serve",
			target = 6,
			rewards = { gold = 300, tier_points = 60, items = { "Suzurimon's Bell Chime Dango" } },
			difficulty = 4,
			companion_unlock = "suzurimon",
			subtext = "The guardian chime rings with joyful purity. Suzurimon pledges her eternal protection to keep your kitchen's rhythm steady forever!",
		},

		-- ── 4. WASABIMON QUESTLINE ────────────────────────────────
		{
			id = "quest_wasabimon_1",
			name = "The Ascetic's Challenge",
			description = "Gather 8 Zunda Leaves from the mountain trails",
			icon = "🌿",
			type = "gather",
			target = 8,
			target_item = "Zunda Leaf",
			rewards = { gold = 80, tier_points = 15, items = { "Zunda Root" } },
			difficulty = 2,
			subtext = "Wasabimon glares from atop a river boulder. 'Show me you have the endurance to harvest in mountain rapids! OSS!'",
		},
		{
			id = "quest_wasabimon_2",
			name = "Blade of Pungent Discipline",
			description = "Cook 3 dishes under 6 seconds each with sharp speed",
			icon = "🔪",
			type = "cook_speed",
			target = 3,
			max_cook_time = 6,
			rewards = { gold = 150, tier_points = 30, items = { "Wasabimon's Pungent Zunda Soba" }, bond_tier = 2 },
			difficulty = 3,
			subtext = "Wasabimon strikes his wooden staff on the ground. 'Speed! Focus! No wasted movements! Let the pungency wake your soul!'",
		},
		{
			id = "quest_wasabimon_3",
			name = "Master of the Mountain Stream",
			description = "Cook Wasabimon's Pungent Zunda Soba and serve 6 guests",
			icon = "🌿",
			type = "serve",
			target = 6,
			rewards = { gold = 300, tier_points = 60, items = { "Wasabimon's Pungent Zunda Soba" } },
			difficulty = 4,
			companion_unlock = "wasabimon",
			subtext = "Wasabimon grunts in deep approval and bows with clenched fists. 'You have the heart of a true culinary monk. I shall walk behind you! OSS!'",
		},

		-- ── 5. YURIMON QUESTLINE ──────────────────────────────────
		{
			id = "quest_yurimon_1",
			name = "A Courtier in the Village",
			description = "Gather 5 Sweet Peas and 5 Pea Flowers",
			icon = "🪷",
			type = "gather",
			target = 5,
			target_item = "Sweet Pea",
			rewards = { gold = 80, tier_points = 15, items = { "Gold" } },
			difficulty = 2,
			subtext = "Lady Yurimon gracefully fans herself near the blossom grove. She admires the natural beauty of the village far more than artificial palace gardens.",
		},
		{
			id = "quest_yurimon_2",
			name = "Royal Plating Aesthetics",
			description = "Achieve 4 Great or Perfect cooks to satisfy imperial standards",
			icon = "👑",
			type = "cook_great",
			target = 4,
			rewards = { gold = 160, tier_points = 35, items = { "Yurimon's Imperial Lily Glaze" }, bond_tier = 2 },
			difficulty = 3,
			subtext = "Yurimon watches your presentation with sparkling eyes. 'Such sublime curvature! The high nobles in Kyoto never cooked with such heart!'",
		},
		{
			id = "quest_yurimon_3",
			name = "Empress of the Village Hearth",
			description = "Earn 200 gold from serving guests",
			icon = "🪷",
			type = "earn_gold",
			target = 200,
			rewards = { gold = 350, tier_points = 70, items = { "Yurimon's Imperial Lily Glaze" } },
			difficulty = 4,
			companion_unlock = "yurimon",
			subtext = "Yurimon curtsies with regal grace. 'My exile from court was destiny—for here beside your stove, I have found true imperial glory!'",
		},

		-- ── 6. KINAKOMON QUESTLINE ────────────────────────────────
		{
			id = "quest_kinakomon_1",
			name = "The Golden Mill's Scent",
			description = "Harvest 10 Wheat from the village fields",
			icon = "🌾",
			type = "gather",
			target = 10,
			target_item = "Wheat",
			rewards = { gold = 80, tier_points = 15, items = { "Bread" } },
			difficulty = 1,
			subtext = "A comforting aroma of toasted soybean flour drifts from the old windmill. Kinakomon is bustling around, fretting that the chefs look too thin.",
		},
		{
			id = "quest_kinakomon_2",
			name = "Grandmother's Hearty Dough",
			description = "Bake 4 Bread dishes to feed the village",
			icon = "🥖",
			type = "cook",
			target = 4,
			target_item = "Bread",
			rewards = { gold = 150, tier_points = 30, items = { "Kinakomon's Golden Dust Dango" }, bond_tier = 2 },
			difficulty = 2,
			subtext = "Kinakomon dusts your apron with golden roasted flour. 'Knead with love, dearie! Good food builds strong bones and happy spirits!'",
		},
		{
			id = "quest_kinakomon_3",
			name = "Golden Dust Family",
			description = "Cook Kinakomon's Golden Dust Dango and serve 6 guests",
			icon = "🌾",
			type = "serve",
			target = 6,
			rewards = { gold = 300, tier_points = 60, items = { "Kinakomon's Golden Dust Dango" } },
			difficulty = 3,
			companion_unlock = "kinakomon",
			subtext = "Kinakomon hugs you warmly with tears in her eyes. 'You'll never go hungry with an old mill grandma by your side, sweetheart!'",
		},

		-- ── 7. KUROYURIMON QUESTLINE ──────────────────────────────
		{
			id = "quest_kuroyurimon_1",
			name = "Whispers from the Manor",
			description = "Gather 5 Zunda Berries in the shadowed grove",
			icon = "🥀",
			type = "gather",
			target = 5,
			target_item = "Zunda Berry",
			rewards = { gold = 80, tier_points = 15, items = { "Zunda Berry" } },
			difficulty = 2,
			subtext = "A theatrical voice echoes from the trees: 'TREMBLE MORTAL, FOR THE BLACK LILY AWAKENS!' ...followed by a tiny squeak and the sound of dropped books.",
		},
		{
			id = "quest_kuroyurimon_2",
			name = "The Grimoire of Sweet Despair",
			description = "Achieve 3 Perfect cooks while enveloped in shadows",
			icon = "📖",
			type = "cook_perfect",
			target = 3,
			rewards = { gold = 150, tier_points = 30, items = { "Kuroyurimon's Eclipse Velvet Tart" }, bond_tier = 2 },
			difficulty = 3,
			subtext = "Kuroyurimon chants dramatic dark Latin verses over your stove, blushing furiously whenever you catch her peeking at her recipe cheat sheet.",
		},
		{
			id = "quest_kuroyurimon_3",
			name = "Unmasked Sovereign",
			description = "Cook Kuroyurimon's Eclipse Velvet Tart and serve 5 guests",
			icon = "🥀",
			type = "serve",
			target = 5,
			rewards = { gold = 300, tier_points = 60, items = { "Kuroyurimon's Eclipse Velvet Tart" } },
			difficulty = 4,
			companion_unlock = "kuroyurimon",
			subtext = "Kuroyurimon drops her ominous staff and gives an embarrassed smile. 'I-if you really want a clumsy bookworm ghost around... I'll protect your pans forever!'",
		},

		-- ── 8. MATCHAMON QUESTLINE ────────────────────────────────
		{
			id = "quest_matchamon_1",
			name = "Path of the Silent Kettle",
			description = "Gather 6 Pea Flowers from the pavilion garden",
			icon = "🍵",
			type = "gather",
			target = 6,
			target_item = "Pea Flower",
			rewards = { gold = 80, tier_points = 15, items = { "Pea Flower Tea" } },
			difficulty = 2,
			subtext = "Matchamon sits in quiet meditation beside the tea pavilion stream. The stone water basin fills with crystalline mountain dew.",
		},
		{
			id = "quest_matchamon_2",
			name = "Flow of the Bamboo Whisk",
			description = "Brew 4 Pea Flower Tea dishes with serene tempo",
			icon = "🌿",
			type = "cook",
			target = 4,
			target_item = "Pea Flower Tea",
			rewards = { gold = 150, tier_points = 30, items = { "Matchamon's Ceremonial Froth Bowl" }, bond_tier = 2 },
			difficulty = 3,
			subtext = "Matchamon demonstrates the four principles of Chado: Harmony, Respect, Purity, and Tranquility. Your kitchen enters a meditative flow.",
		},
		{
			id = "quest_matchamon_3",
			name = "Enlightened Hearth",
			description = "Cook Matchamon's Ceremonial Froth Bowl and serve 6 guests",
			icon = "🍵",
			type = "serve",
			target = 6,
			rewards = { gold = 300, tier_points = 60, items = { "Matchamon's Ceremonial Froth Bowl" } },
			difficulty = 4,
			companion_unlock = "matchamon",
			subtext = "Matchamon offers a solemn bow of lifelong camaraderie. 'Together, our kitchen shall be an oasis of tranquil flavor for all weary travelers.'",
		},

		-- ── 9. SHISOMON QUESTLINE ─────────────────────────────────
		{
			id = "quest_shisomon_1",
			name = "The Herbalist's Specimen",
			description = "Gather 8 Zunda Leaves for botanical analysis",
			icon = "🍃",
			type = "gather",
			target = 8,
			target_item = "Zunda Leaf",
			rewards = { gold = 80, tier_points = 15, items = { "Zunda Root" } },
			difficulty = 2,
			subtext = "Shisomon excitedly sniffs your gathering basket. 'EUREKA! The volatile aromatic compounds in these specimens are exceptional!'",
		},
		{
			id = "quest_shisomon_2",
			name = "Fermentation Laboratory",
			description = "Craft 3 Seasonal Salad dishes to test pickling reaction rates",
			icon = "🧪",
			type = "cook",
			target = 3,
			target_item = "Seasonal Salad",
			rewards = { gold = 150, tier_points = 30, items = { "Shisomon's Pickled Perilla Wrap" }, bond_tier = 2 },
			difficulty = 3,
			subtext = "Shisomon measures brine salinity with meticulous precision. 'Observe! The microbial culture is blooming at peak efficiency!'",
		},
		{
			id = "quest_shisomon_3",
			name = "Master Alchemist of Flavor",
			description = "Cook Shisomon's Pickled Perilla Wrap and serve 6 guests",
			icon = "🍃",
			type = "serve",
			target = 6,
			rewards = { gold = 300, tier_points = 60, items = { "Shisomon's Pickled Perilla Wrap" } },
			difficulty = 4,
			companion_unlock = "shisomon",
			subtext = "Shisomon adjusts his goggles with wild excitement. 'Our collaborative culinary alchemy is revolutionary! I shall be your chief scientist forever!'",
		},

		-- ── 10. KARINTOMON QUESTLINE ──────────────────────────────
		{
			id = "quest_karintomon_1",
			name = "The Carnival Sugar Rush",
			description = "Gather 6 Apples for the festival fryer",
			icon = "🏮",
			type = "gather",
			target = 6,
			target_item = "Apple",
			rewards = { gold = 80, tier_points = 15, items = { "Apple" } },
			difficulty = 1,
			subtext = "Karintomon pounds a festival taiko drum on the village plaza. 'STEP RIGHT UP! The carnival needs ingredients for the ultimate molasses fry!'",
		},
		{
			id = "quest_karintomon_2",
			name = "Jackpot Sizzle",
			description = "Achieve 4 Great or Perfect cooks to trigger carnival energy",
			icon = "💥",
			type = "cook_great",
			target = 4,
			rewards = { gold = 160, tier_points = 35, items = { "Karintomon's Crisp Molasses Crunch" }, bond_tier = 2 },
			difficulty = 2,
			subtext = "Karintomon spins a giant prize wheel over your stove. 'LOOK AT THOSE SPARKS! Every dish is rolling with jackpot energy!'",
		},
		{
			id = "quest_karintomon_3",
			name = "Grand Carnival Champion",
			description = "Cook Karintomon's Crisp Molasses Crunch and serve 8 guests",
			icon = "🏮",
			type = "serve",
			target = 8,
			rewards = { gold = 320, tier_points = 65, items = { "Karintomon's Crisp Molasses Crunch" } },
			difficulty = 3,
			companion_unlock = "karintomon",
			subtext = "Confetti and fireworks erupt! Karintomon raises your spatula high. 'WASSHOI! We are the greatest carnival duo in history! Let's roll!'",
		},

		-- ── 11. TSUKIMIDAMON QUESTLINE ────────────────────────────
		{
			id = "quest_tsukimidamon_1",
			name = "Silver Light on the Meadow",
			description = "Gather 6 Zunda Peas under the evening sky",
			icon = "🌕",
			type = "gather",
			target = 6,
			target_item = "Zunda Pea",
			rewards = { gold = 80, tier_points = 15, items = { "Zunda Pea" } },
			difficulty = 2,
			subtext = "Tsukimidamon floats gently above the dew-covered meadow, tracing silver constellations with a glowing fingertip.",
		},
		{
			id = "quest_tsukimidamon_2",
			name = "Dumplings for the Full Moon",
			description = "Craft 3 Zunda Mochi dishes with celestial symmetry",
			icon = "🍡",
			type = "cook",
			target = 3,
			target_item = "Zunda Mochi",
			rewards = { gold = 150, tier_points = 30, items = { "Tsukimidamon's Lunar Dumpling Plate" }, bond_tier = 2 },
			difficulty = 3,
			subtext = "Tsukimidamon smiles softly as the round dumplings take shape. 'Each one mirrors the bright moon, bringing tranquility to those who partake.'",
		},
		{
			id = "quest_tsukimidamon_3",
			name = "The Lunar Companion",
			description = "Cook Tsukimidamon's Lunar Dumpling Plate and serve 6 guests",
			icon = "🌕",
			type = "serve",
			target = 6,
			rewards = { gold = 300, tier_points = 60, items = { "Tsukimidamon's Lunar Dumpling Plate" } },
			difficulty = 4,
			companion_unlock = "tsukimidamon",
			subtext = "The full moon shines directly into your kitchen. Tsukimidamon takes your hand with celestial warmth. 'I shall illuminate your night shifts forever.'",
		},

		-- ── 12. HOSHIDAMON QUESTLINE ──────────────────────────────
		{
			id = "quest_hoshidamon_1",
			name = "The Hermit's Harvest",
			description = "Gather 6 Apples and 4 Zunda Roots",
			icon = "☀️",
			type = "gather",
			target = 6,
			target_item = "Apple",
			rewards = { gold = 80, tier_points = 15, items = { "Apple" } },
			difficulty = 2,
			subtext = "Hoshidamon sits on a wooden stool outside the village storehouse, carefully peeling winter persimmons with an old horn knife.",
		},
		{
			id = "quest_hoshidamon_2",
			name = "The Art of Slow Simmer",
			description = "Cook 3 Royal Stew dishes with patient flame",
			icon = "🍲",
			type = "cook",
			target = 3,
			target_item = "Royal Stew",
			rewards = {
				gold = 150,
				tier_points = 30,
				items = { "Hoshidamon's Sun-Cured Persimmon Paste" },
				bond_tier = 2,
			},
			difficulty = 3,
			subtext = "Hoshidamon gestures to the simmering pot. 'Hear the gentle murmur? That is time transforming simple roots into pure gold. Never rush it.'",
		},
		{
			id = "quest_hoshidamon_3",
			name = "Wisdom of Sun and Frost",
			description = "Cook Hoshidamon's Sun-Cured Persimmon Paste and serve 6 guests",
			icon = "☀️",
			type = "serve",
			target = 6,
			rewards = { gold = 300, tier_points = 60, items = { "Hoshidamon's Sun-Cured Persimmon Paste" } },
			difficulty = 4,
			companion_unlock = "hoshidamon",
			subtext = "Hoshidamon laughs with deep belly warmth. 'In all my seventy winters, I have never tasted such faithful craft. Count this old hermit as your lifelong partner!'",
		},
	},

	-- ── Canon Companion Quests (R6 Lore Cohort) ──────────────────────────────

	quest_kiritandamon_1 = {
		id = "quest_kiritandamon_1",
		name = "The Analytical Guest",
		description = "Kiritandamon has arrived with a clipboard. She wants to evaluate your technique. Complete 5 precision cooks (Great or better).",
		icon = "📐",
		type = "cook_quality",
		target = 5,
		rewards = { gold = 120, tier_points = 20, items = {} },
		difficulty = 3,
	},
	quest_kiritandamon_2 = {
		id = "quest_kiritandamon_2",
		name = "The Efficiency Report",
		description = "Kiritandamon has identified an 18% throughput deficit. Serve 12 guests without a single timeout.",
		icon = "📊",
		type = "serve_guests_no_timeout",
		target = 12,
		rewards = { gold = 200, tier_points = 35, items = {} },
		difficulty = 4,
	},
	quest_kiritandamon_3 = {
		id = "quest_kiritandamon_3",
		name = "The Anomalous Variable",
		description = "Achieve 3 Perfect cooks of Kiritandamon's Precision Cut Tempura. She will not admit she is impressed. Her log will record it.",
		icon = "📐",
		type = "cook_quality",
		target = 3,
		target_item = "Kiritandamon's Precision Cut Tempura",
		rewards = { gold = 350, tier_points = 60, items = { "Analytical Apron" } },
		difficulty = 5,
		companion_unlock = "kiritandamon",
		subtext = "Kiritandamon closes her clipboard. 'Column {player} now has 3 entries. It is the longest column. I am — this is not relevant — glad.'",
	},

	quest_itakodamon_1 = {
		id = "quest_itakodamon_1",
		name = "The Watching Oracle",
		description = "A presence has been watching since your 1st guest. Serve your 100th lifetime guest.",
		icon = "🔮",
		type = "serve_guests",
		target = 100,
		rewards = { gold = 100, tier_points = 18, items = {} },
		difficulty = 2,
	},
	quest_itakodamon_2 = {
		id = "quest_itakodamon_2",
		name = "The Ancient Menu",
		description = "Itakodamon speaks of recipes older than the village. Craft Itakodamon's Oracle Root Broth 3 times.",
		icon = "🫙",
		type = "cook_recipe",
		target = 3,
		target_item = "Itakodamon's Oracle Root Broth",
		rewards = { gold = 180, tier_points = 30, items = {} },
		difficulty = 3,
	},
	quest_itakodamon_3 = {
		id = "quest_itakodamon_3",
		name = "The Oracle's Gift",
		description = "Itakodamon will speak of the Zunda Arrow to one who has earned it. Achieve Bond Tier 3 with Zundamon.",
		icon = "🔮",
		type = "companion_bond",
		target = 3,
		target_item = "zundamon",
		rewards = { gold = 400, tier_points = 65, items = { "Oracle's Pendant" } },
		difficulty = 4,
		companion_unlock = "itakodamon",
		subtext = "Itakodamon is silent for a long moment. 'I was there when the Arrow was named. I will not tell you what was said. But I will sit beside you while you cook.'",
	},

	quest_zunkodamon_1 = {
		id = "quest_zunkodamon_1",
		name = "The Warrior's Entry",
		description = "Zunkodamon has reviewed the menu and found it worthy. Serve a guest worth 200+ gold in a single transaction.",
		icon = "⚔️",
		type = "single_serve_gold",
		target = 200,
		rewards = { gold = 130, tier_points = 22, items = {} },
		difficulty = 3,
	},
	quest_zunkodamon_2 = {
		id = "quest_zunkodamon_2",
		name = "The Campaign",
		description = "Zunkodamon calls it a campaign. Serve 20 guests with no failures during peak hours.",
		icon = "🍜",
		type = "serve_guests",
		target = 20,
		rewards = { gold = 220, tier_points = 38, items = {} },
		difficulty = 4,
	},
	quest_zunkodamon_3 = {
		id = "quest_zunkodamon_3",
		name = "Victory Feast",
		description = "Prove yourself to the warrior-chef. Perfect-cook Zunkodamon's Victory Feast and serve it to 3 different guests.",
		icon = "⚔️",
		type = "serve_specific",
		target = 3,
		target_item = "Zunkodamon's Victory Feast",
		rewards = { gold = 380, tier_points = 62, items = { "Warrior's Apron" } },
		difficulty = 5,
		companion_unlock = "zunkodamon",
		subtext = "Zunkodamon sheathes her ladle with ceremony. 'The kitchen held. You held. This is the victory that matters, chef.'",
	},

	quest_zunabunny_1 = {
		id = "quest_zunabunny_1",
		name = "Spectacular Failure",
		description = "Zunabunny appeared when you burned a dish. Fail a recipe (Poor quality) once. She will explain this is completely normal.",
		icon = "🐰",
		type = "cook_quality_poor",
		target = 1,
		rewards = { gold = 50, tier_points = 8, items = {} },
		difficulty = 1,
	},
	quest_zunabunny_2 = {
		id = "quest_zunabunny_2",
		name = "The Chaotic Method",
		description = "Cook Zunabunny's Accidental Masterpiece 5 times. Each result will be different. This is the point.",
		icon = "🎲",
		type = "cook_recipe",
		target = 5,
		target_item = "Zunabunny's Accidental Masterpiece",
		rewards = { gold = 160, tier_points = 28, items = {} },
		difficulty = 2,
	},
	quest_zunabunny_3 = {
		id = "quest_zunabunny_3",
		name = "Best Friends, Statistically",
		description = "Zunabunny has decided you are her favorite person. Earn 15 Lucky Chaos bonus procs (RNG bonus triggers from serving).",
		icon = "🐰",
		type = "lucky_chaos_procs",
		target = 15,
		rewards = { gold = 280, tier_points = 48, items = { "Chaos Ears Accessory" } },
		difficulty = 3,
		companion_unlock = "zunabunny",
		subtext = "Zunabunny bounces with barely contained joy. 'YOU ARE MY FAVORITE PERSON!!! I TOLD ZUNDAMON!!! SHE SAID SHE KNOWS!!! WE BOTH KNOW!!! 🐰'",
	},

	quest_nanonadamon_1 = {
		id = "quest_nanonadamon_1",
		name = "The Fragment Stirs",
		description = "Something ancient has noticed you. Reach Bond Tier 2 with Zundamon.",
		icon = "🏹",
		type = "companion_bond",
		target = 2,
		target_item = "zundamon",
		rewards = { gold = 80, tier_points = 15, items = {} },
		difficulty = 2,
	},
	quest_nanonadamon_2 = {
		id = "quest_nanonadamon_2",
		name = "The Arrow's Recipe",
		description = "Cook Nanonadamon's First Recipe. It requires rare ingredients. The ingredients are not rare by chance.",
		icon = "🫛",
		type = "cook_recipe",
		target = 1,
		target_item = "Nanonadamon's First Recipe",
		rewards = { gold = 250, tier_points = 45, items = {} },
		difficulty = 5,
	},
	quest_nanonadamon_3 = {
		id = "quest_nanonadamon_3",
		name = "The Origin",
		description = "Nanonadamon has waited centuries for this moment. Complete 'The Zunda Origin' grand questline.",
		icon = "🏹",
		type = "complete_grand_quest",
		target = 1,
		target_item = "grand_zunda_origin",
		rewards = { gold = 1000, tier_points = 150, items = { "Arrow Fragment Charm", "Nanonadamon Dex Card" } },
		difficulty = 5,
		companion_unlock = "nanonadamon",
		subtext = "Nanonadamon is quiet for a long time. Then: 'You arrived at the end of the story, のだ. I have been waiting here for you, のだ. I did not know it would be you, のだ. But it was always going to be someone like you, のだ.'",
	},

	-- ── Grand Questlines ──────────────────────────────────────────────────────
	-- Arc 1: The Zunda Origin (10 stages, unlocks Nanonadamon)
	-- Arc 2: Culinary Ascension (10 stages, endgame prestige arc)
	-- Arc 3: The Great Tohoku Reunion (10 stages, reunites all canon spirits)

	-- ─── Arc 1: The Zunda Origin ─────────────────────────────────────────────

	grand_origin_1 = {
		id = "grand_origin_1",
		name = "The Zunda Origin — I: The Kitchen That Remembers",
		description = "Something in the kitchen is older than the kitchen. Begin by cooking Zunda Mochi 3 times at Perfect quality and listening to what Zundamon says.",
		icon = "🌱",
		type = "cook_quality",
		target = 3,
		target_item = "Zunda Mochi",
		rewards = { gold = 200, tier_points = 30, items = {} },
		difficulty = 2,
		grand_quest_id = "grand_zunda_origin",
		stage = 1,
	},
	grand_origin_2 = {
		id = "grand_origin_2",
		name = "The Zunda Origin — II: The Elder's Record",
		description = "The Village Elder has documents that predate the village. Serve the Elder as a guest 3 times.",
		icon = "🏮",
		type = "serve_specific_npc",
		target = 3,
		target_item = "elder",
		rewards = { gold = 220, tier_points = 32, items = {} },
		difficulty = 2,
		grand_quest_id = "grand_zunda_origin",
		stage = 2,
	},
	grand_origin_3 = {
		id = "grand_origin_3",
		name = "The Zunda Origin — III: The Cracked Bell Speaks",
		description = "Suzurimon knows things from the bottom of the drowned shrine. Reach Bond Tier 2 with Suzurimon.",
		icon = "🔔",
		type = "companion_bond",
		target = 2,
		target_item = "suzurimon",
		rewards = { gold = 250, tier_points = 35, items = {} },
		difficulty = 3,
		grand_quest_id = "grand_zunda_origin",
		stage = 3,
	},
	grand_origin_4 = {
		id = "grand_origin_4",
		name = "The Zunda Origin — IV: The Ink Record",
		description = "Sumimon witnessed the Zunda Arrow in a painting she never signed. Reach Bond Tier 2 with Sumimon.",
		icon = "🖌️",
		type = "companion_bond",
		target = 2,
		target_item = "sumimon",
		rewards = { gold = 260, tier_points = 38, items = {} },
		difficulty = 3,
		grand_quest_id = "grand_zunda_origin",
		stage = 4,
	},
	grand_origin_5 = {
		id = "grand_origin_5",
		name = "The Zunda Origin — V: The Oracle's Direction",
		description = "Itakodamon will not speak of the Arrow directly. But she will point. Unlock Itakodamon and reach Bond Tier 1 with her.",
		icon = "🔮",
		type = "companion_bond",
		target = 1,
		target_item = "itakodamon",
		rewards = { gold = 300, tier_points = 42, items = {} },
		difficulty = 4,
		grand_quest_id = "grand_zunda_origin",
		stage = 5,
	},
	grand_origin_6 = {
		id = "grand_origin_6",
		name = "The Zunda Origin — VI: The Warrior Remembers",
		description = "Zunkodamon wielded Zundamon as an arrow, once. She will confirm this to someone she trusts. Reach Bond Tier 2 with Zunkodamon.",
		icon = "⚔️",
		type = "companion_bond",
		target = 2,
		target_item = "zunkodamon",
		rewards = { gold = 320, tier_points = 45, items = {} },
		difficulty = 4,
		grand_quest_id = "grand_zunda_origin",
		stage = 6,
	},
	grand_origin_7 = {
		id = "grand_origin_7",
		name = "The Zunda Origin — VII: The Recipe Before Time",
		description = "The oldest recipe in the kitchen is not in any cookbook. Perfect-cook Nanonadamon's First Recipe.",
		icon = "🏹",
		type = "cook_quality",
		target = 1,
		target_item = "Nanonadamon's First Recipe",
		rewards = { gold = 400, tier_points = 55, items = {} },
		difficulty = 5,
		grand_quest_id = "grand_zunda_origin",
		stage = 7,
	},
	grand_origin_8 = {
		id = "grand_origin_8",
		name = "The Zunda Origin — VIII: The Mascot Knows",
		description = "Zunabunny holds a piece of the answer, accidentally. Reach Bond Tier 2 with Zunabunny.",
		icon = "🐰",
		type = "companion_bond",
		target = 2,
		target_item = "zunabunny",
		rewards = { gold = 350, tier_points = 48, items = {} },
		difficulty = 3,
		grand_quest_id = "grand_zunda_origin",
		stage = 8,
	},
	grand_origin_9 = {
		id = "grand_origin_9",
		name = "The Zunda Origin — IX: The Arrow's Memory",
		description = "The final memory is a perfect moment. Zundamon·Shin must be unlocked (evolve Zundamon).",
		icon = "🌿",
		type = "unlock_evolved",
		target = 1,
		target_item = "zundamon_shin",
		rewards = { gold = 500, tier_points = 70, items = { "Zunda Light Shard" } },
		difficulty = 5,
		grand_quest_id = "grand_zunda_origin",
		stage = 9,
	},
	grand_origin_10 = {
		id = "grand_origin_10",
		name = "The Zunda Origin — X: The Fragment's Return",
		description = "Nanonadamon has been waiting. At the end of all the questions, cook one final Zunda Paradise at Perfect quality. She will speak.",
		icon = "🏹",
		type = "cook_quality",
		target = 1,
		target_item = "Zunda Paradise",
		rewards = { gold = 1500, tier_points = 200, items = { "Nanonadamon True Form Token", "Zunda Origin Badge" } },
		difficulty = 5,
		grand_quest_id = "grand_zunda_origin",
		stage = 10,
		is_finale = true,
	},

	-- ─── Arc 2: Culinary Ascension ────────────────────────────────────────────

	grand_ascension_1 = {
		id = "grand_ascension_1",
		name = "Culinary Ascension — I: The Claim",
		description = "You have fed this village for long enough to make a claim. Reach Prestige Tier 1.",
		icon = "⭐",
		type = "prestige_tier",
		target = 1,
		rewards = { gold = 300, tier_points = 40, items = {} },
		difficulty = 3,
		grand_quest_id = "grand_culinary_ascension",
		stage = 1,
	},
	grand_ascension_2 = {
		id = "grand_ascension_2",
		name = "Culinary Ascension — II: The Tournament Entry",
		description = "A Grand Chef enters tournaments. Achieve a Silver Fork ranking or better in any weekly tournament.",
		icon = "🏆",
		type = "tournament_rank",
		target = 50,
		rewards = { gold = 350, tier_points = 45, items = {} },
		difficulty = 3,
		grand_quest_id = "grand_culinary_ascension",
		stage = 2,
	},
	grand_ascension_3 = {
		id = "grand_ascension_3",
		name = "Culinary Ascension — III: The Perfect Party",
		description = "Assemble a party of 3 companions with an active triple-type synergy bonus and serve 10 guests.",
		icon = "✨",
		type = "serve_with_synergy",
		target = 10,
		rewards = { gold = 400, tier_points = 50, items = {} },
		difficulty = 4,
		grand_quest_id = "grand_culinary_ascension",
		stage = 3,
	},
	grand_ascension_4 = {
		id = "grand_ascension_4",
		name = "Culinary Ascension — IV: The Seasonal Rite",
		description = "Participate in a seasonal event and complete all 7 days of its quest chain.",
		icon = "🌸",
		type = "complete_seasonal_chain",
		target = 1,
		rewards = { gold = 450, tier_points = 55, items = {} },
		difficulty = 3,
		grand_quest_id = "grand_culinary_ascension",
		stage = 4,
	},
	grand_ascension_5 = {
		id = "grand_ascension_5",
		name = "Culinary Ascension — V: The Bond Network",
		description = "A Grand Chef knows all their companions. Reach Bond Tier 2 with 10 different companions.",
		icon = "💛",
		type = "companion_bond_count",
		target = 10,
		rewards = { gold = 500, tier_points = 65, items = { "Golden Bond Ribbon" } },
		difficulty = 4,
		grand_quest_id = "grand_culinary_ascension",
		stage = 5,
	},
	grand_ascension_6 = {
		id = "grand_ascension_6",
		name = "Culinary Ascension — VI: The Expert Menu",
		description = "Master the hardest dishes. Perfect-cook 5 recipes with Expert difficulty rating.",
		icon = "👨‍🍳",
		type = "cook_expert",
		target = 5,
		rewards = { gold = 600, tier_points = 75, items = {} },
		difficulty = 5,
		grand_quest_id = "grand_culinary_ascension",
		stage = 6,
	},
	grand_ascension_7 = {
		id = "grand_ascension_7",
		name = "Culinary Ascension — VII: The Gold Ladle",
		description = "Prove your tournament standing. Achieve Gold Ladle ranking (top 10) in any weekly tournament.",
		icon = "🥉",
		type = "tournament_rank",
		target = 10,
		rewards = { gold = 700, tier_points = 85, items = {} },
		difficulty = 5,
		grand_quest_id = "grand_culinary_ascension",
		stage = 7,
	},
	grand_ascension_8 = {
		id = "grand_ascension_8",
		name = "Culinary Ascension — VIII: The Evolved Kitchen",
		description = "Evolve 3 companions to their evolved forms.",
		icon = "🦋",
		type = "evolve_companions",
		target = 3,
		rewards = { gold = 800, tier_points = 100, items = { "Evolution Mastery Badge" } },
		difficulty = 5,
		grand_quest_id = "grand_culinary_ascension",
		stage = 8,
	},
	grand_ascension_9 = {
		id = "grand_ascension_9",
		name = "Culinary Ascension — IX: The Second Prestige",
		description = "The ascension is not complete at one prestige. Reach Prestige Tier 2.",
		icon = "🌟",
		type = "prestige_tier",
		target = 2,
		rewards = { gold = 1000, tier_points = 120, items = {} },
		difficulty = 5,
		grand_quest_id = "grand_culinary_ascension",
		stage = 9,
	},
	grand_ascension_10 = {
		id = "grand_ascension_10",
		name = "Culinary Ascension — X: The Grand Chef",
		description = "One last proof. Win the Zunda Grand Master title in a weekly tournament.",
		icon = "🏆",
		type = "tournament_rank",
		target = 1,
		rewards = {
			gold = 3000,
			tier_points = 300,
			items = { "Grand Chef Crown", "Grand Chef Title", "Zunda Ascension Badge" },
		},
		difficulty = 5,
		grand_quest_id = "grand_culinary_ascension",
		stage = 10,
		is_finale = true,
	},

	-- ─── Arc 3: The Great Tohoku Reunion ─────────────────────────────────────

	grand_reunion_1 = {
		id = "grand_reunion_1",
		name = "The Great Tohoku Reunion — I: The Summons",
		description = "The Tohoku spirits have not gathered in one kitchen since the Zunda Arrow was forged. Someone must send the summons. Cook one of Zundamon's signature dishes at Perfect quality.",
		icon = "🌱",
		type = "cook_quality",
		target = 1,
		target_item = "Zunda Paradise",
		rewards = { gold = 200, tier_points = 28, items = {} },
		difficulty = 2,
		grand_quest_id = "grand_tohoku_reunion",
		stage = 1,
	},
	grand_reunion_2 = {
		id = "grand_reunion_2",
		name = "The Great Tohoku Reunion — II: Kiritan's Condition",
		description = "Kiritandamon will attend if you can prove the kitchen meets her standards. Achieve Bond Tier 2 with Kiritandamon.",
		icon = "📐",
		type = "companion_bond",
		target = 2,
		target_item = "kiritandamon",
		rewards = { gold = 250, tier_points = 34, items = {} },
		difficulty = 3,
		grand_quest_id = "grand_tohoku_reunion",
		stage = 2,
	},
	grand_reunion_3 = {
		id = "grand_reunion_3",
		name = "The Great Tohoku Reunion — III: Itako's Preparation",
		description = "Itakodamon says the gathering requires something cooked from all three Tohoku sister-spirit recipes. Cook Itakodamon's Oracle Root Broth, Kiritandamon's Precision Cut Tempura, and Zunkodamon's Victory Feast.",
		icon = "🔮",
		type = "cook_recipe_set",
		target = 3,
		rewards = { gold = 320, tier_points = 42, items = {} },
		difficulty = 4,
		grand_quest_id = "grand_tohoku_reunion",
		stage = 3,
	},
	grand_reunion_4 = {
		id = "grand_reunion_4",
		name = "The Great Tohoku Reunion — IV: Zunko's Challenge",
		description = "Zunkodamon insists the reunion kitchen must be proven under pressure. Survive a Challenge Mode wave of 10 without any guest leaving unhappy.",
		icon = "⚔️",
		type = "challenge_wave",
		target = 10,
		rewards = { gold = 380, tier_points = 50, items = {} },
		difficulty = 4,
		grand_quest_id = "grand_tohoku_reunion",
		stage = 4,
	},
	grand_reunion_5 = {
		id = "grand_reunion_5",
		name = "The Great Tohoku Reunion — V: The Mascot's Role",
		description = "Zunabunny has a very important job in the reunion: she will knock something over at the perfect moment. Reach Bond Tier 3 with Zunabunny.",
		icon = "🐰",
		type = "companion_bond",
		target = 3,
		target_item = "zunabunny",
		rewards = { gold = 350, tier_points = 46, items = {} },
		difficulty = 3,
		grand_quest_id = "grand_tohoku_reunion",
		stage = 5,
	},
	grand_reunion_6 = {
		id = "grand_reunion_6",
		name = "The Great Tohoku Reunion — VI: What Zundamon Remembers",
		description = "The reunion cannot happen without its center. Reach Bond Tier 3 with Zundamon.",
		icon = "🌱",
		type = "companion_bond",
		target = 3,
		target_item = "zundamon",
		rewards = { gold = 450, tier_points = 58, items = {} },
		difficulty = 4,
		grand_quest_id = "grand_tohoku_reunion",
		stage = 6,
	},
	grand_reunion_7 = {
		id = "grand_reunion_7",
		name = "The Great Tohoku Reunion — VII: The Oldest Guest",
		description = "Nanonadamon says she will attend as a witness, not a participant. She asks that you serve 5 Ancient-type guests at Perfect quality.",
		icon = "🏹",
		type = "serve_type_perfect",
		target = 5,
		target_item = "ancient_type",
		rewards = { gold = 500, tier_points = 65, items = {} },
		difficulty = 5,
		grand_quest_id = "grand_tohoku_reunion",
		stage = 7,
	},
	grand_reunion_8 = {
		id = "grand_reunion_8",
		name = "The Great Tohoku Reunion — VIII: The Preparation Feast",
		description = "Before the spirits gather, the kitchen must be fed. Serve 30 guests in a single session.",
		icon = "🍜",
		type = "serve_guests",
		target = 30,
		rewards = { gold = 550, tier_points = 72, items = {} },
		difficulty = 4,
		grand_quest_id = "grand_tohoku_reunion",
		stage = 8,
	},
	grand_reunion_9 = {
		id = "grand_reunion_9",
		name = "The Great Tohoku Reunion — IX: The Arrow Returns",
		description = "Unlock Zundamon·Shin (evolve Zundamon). The reunion cannot happen while she is still the old form.",
		icon = "🌿",
		type = "unlock_evolved",
		target = 1,
		target_item = "zundamon_shin",
		rewards = { gold = 700, tier_points = 90, items = { "Reunion Preparation Medal" } },
		difficulty = 5,
		grand_quest_id = "grand_tohoku_reunion",
		stage = 9,
	},
	grand_reunion_10 = {
		id = "grand_reunion_10",
		name = "The Great Tohoku Reunion — X: The Gathering",
		description = "They are all here. Zundamon·Shin, Kiritandamon, Itakodamon, Zunkodamon, Zunabunny, and Nanonadamon — all in the same kitchen. Cook Zundamon's Banquet at Perfect quality. This is the end of the Tohoku story and the beginning of something else.",
		icon = "🌸",
		type = "cook_quality",
		target = 1,
		target_item = "Zundamon's Banquet",
		rewards = {
			gold = 5000,
			tier_points = 500,
			items = { "Tohoku Reunion Badge", "Great Gathering Title", "Zundamon·Shin Card" },
		},
		difficulty = 5,
		grand_quest_id = "grand_tohoku_reunion",
		stage = 10,
		is_finale = true,
	},
}

return QuestConfig
