#!/usr/bin/env python3
"""
Companion AI Bridge Server — Zundamon's Kitchen V2
===================================================

Lightweight HTTP server (stdlib only) that bridges Roblox → Ollama
for live companion AI chat and custom companion generation.

Endpoints:
    GET  /health               → {"status": "ok"}
    POST /generate-companion   → companion spec JSON
    POST /companion-chat       → {"reply": "..."}

Usage:
    python scripts/companion_ai_server.py [--port 8742] [--host 127.0.0.1]

See docs/LLM_PIPELINE.md for the complete wiring guide.
"""

import argparse
import json
import logging
import sys
import threading
import time
import traceback
from http.server import BaseHTTPRequestHandler, HTTPServer
from pathlib import Path
from typing import Any, Dict

# ── Path setup ────────────────────────────────────────────────────────────────
# Ensure scripts/ is on the path so ollama_client can be imported directly.
SCRIPTS_DIR = Path(__file__).parent
sys.path.insert(0, str(SCRIPTS_DIR))

try:
    from ollama_client import OllamaClient, ZUNDAMON_PERSONA, MODEL_PRESETS
    OLLAMA_AVAILABLE = True
except ImportError:
    OLLAMA_AVAILABLE = False
    print("[WARN] ollama_client.py not found — running in offline-only mode.")

# ── Logging ───────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger("companion_ai_server")

# ── Rate limiting ─────────────────────────────────────────────────────────────
# Simple token-bucket: max N concurrent Ollama requests.
_semaphore = threading.Semaphore(3)

# ── Companion Persona Store ───────────────────────────────────────────────────
# Loaded from CompanionConfig equivalent — a flat JSON snapshot generated by
#   python scripts/export_companion_personas.py
# Falls back to a built-in minimal set if not found.

PERSONA_SNAPSHOT_PATH = SCRIPTS_DIR / "companion_personas.json"

_BUILTIN_PERSONAS: Dict[str, str] = {
    "zundamon":    "You are Zundamon, the village guide and pea-spirit companion. Enthusiastic, ALL CAPS, ends sentences with ~のだ. Loves edamame, cooking, and the player.",
    "ankomon":     "You are Ankomon, a red bean spirit. Sweet-tempered, generous with gold advice, nostalgic for a shop that no longer exists.",
    "cardamon":    "You are Cardamon, a cardamom seedling spirit. Precise, calming, helps players land perfect cooks.",
    "antimon":     "You are Antimon, a minty wisp. Energetic underground explorer who surfaces to point at hidden things.",
    "sakuradamon": "You are Sakuradamon, a blossom spirit. Gentle teacher, petals never fall, carries good lessons on the breeze.",
    "tantanmon":   "You are Tantanmon, a spicy firework spirit. Fast, impatient, very loud. Everything is an emergency.",
    "sumimon":     "You are Sumimon, a melancholic ink-wash scholar spirit. Quiet, precise, views cooking as living calligraphy.",
    "kagamon":     "You are Kagamon, a mirror spirit. Radiant, relentlessly cheerful, hiding hairline cracks with a perfect smile.",
    "suzurimon":   "You are Suzurimon, a drowned shrine bell. Solemn, rhythmic, keeps time because she cannot keep anything else.",
    "wasabimon":   "You are Wasabimon, an alpine ascetic monk. Demanding, blunt, considers patience a virtue and speed a sin.",
    "matchamon":   "You are Matchamon, a tea ceremony master. Slow, deliberate, believes this moment is the only moment.",
    "tsukimidamon":"You are Tsukimidamon, a moon-viewing spirit. Dreamy, nocturnal, shares secrets of the night slowly.",
    "hoshidamon":  "You are Hoshidamon, a sun-dried hermit. Ancient, unhurried, teaches that time is the most important ingredient.",
}


def _load_personas() -> Dict[str, str]:
    if PERSONA_SNAPSHOT_PATH.exists():
        try:
            with open(PERSONA_SNAPSHOT_PATH, "r", encoding="utf-8") as f:
                data = json.load(f)
            log.info("Loaded %d companion personas from %s", len(data), PERSONA_SNAPSHOT_PATH)
            return data
        except Exception as e:
            log.warning("Failed to load persona snapshot: %s — using built-ins.", e)
    return dict(_BUILTIN_PERSONAS)


_PERSONAS = _load_personas()


# ── Fallback replies ──────────────────────────────────────────────────────────

def _offline_fallback_chat(companion_key: str) -> str:
    """Returns a themed offline reply for a companion."""
    fallbacks = {
        "zundamon":    "( I'm somewhere far away right now, nanoda... Find me again soon! 🌱 )",
        "sumimon":     "( ... the brush is still. I will return when the ink is ready. )",
        "suzurimon":   "( ... )",
        "kagamon":     "( I'm always here, always shining! Just... give me a moment. 🪞 )",
        "matchamon":   "( The tea is steeping. I will speak when it is ready. )",
        "tsukimidamon":"( The moon is behind clouds tonight. Ask me again later... 🌕 )",
        "wasabimon":   "( Silence is also an answer. Think about that. )",
    }
    return fallbacks.get(
        companion_key,
        "( I seem to be far away right now. Find me again soon! )"
    )


def _offline_fallback_generate(theme: str) -> Dict[str, Any]:
    """Deterministic companion spec fallback when Ollama is unavailable."""
    hue_seed = sum(ord(c) for c in theme) % 360
    r = int(128 + 80 * __import__("math").sin(__import__("math").radians(hue_seed)))
    g = int(128 + 80 * __import__("math").sin(__import__("math").radians(hue_seed + 120)))
    b = int(128 + 80 * __import__("math").sin(__import__("math").radians(hue_seed + 240)))
    word = next((w for w in theme.split() if len(w) > 2), "Mystery")
    name = "Zunda-" + word[:1].upper() + word[1:12]
    return {
        "name": name.lower().replace(" ", "_"),
        "displayName": name,
        "flavor": f"A quiet little spirit summoned from '{theme}'.",
        "persona": f"You are {name}, a companion born from '{theme}'. You keep the player company while they cook.",
        "emoji": "🌱",
        "glow": [r / 255, g / 255, b / 255],
        "sparkleColors": [
            [r / 255, g / 255, b / 255],
            [min(1.0, r / 255 + 0.2), min(1.0, g / 255 + 0.2), 1.0],
            [1.0, 1.0, 1.0],
        ],
        "buff": {"stat": "gold", "magnitude": 0.05, "description": "+5% gold from serving guests"},
        "signature_recipes": ["Zunda Mochi", "Bread"],
        "_offline": True,
    }


# ── Ollama generation helpers ─────────────────────────────────────────────────

def _generate_companion(theme: str, voice: str) -> Dict[str, Any]:
    if not OLLAMA_AVAILABLE:
        return _offline_fallback_generate(theme)

    client = OllamaClient(model=MODEL_PRESETS.get("dialogue", "gemma4:12b"))
    if not client.is_available():
        log.warning("Ollama not reachable — returning offline fallback.")
        return _offline_fallback_generate(theme)

    system = (
        "You are a creative companion designer for Zundamon's Kitchen, a Roblox cooking game.\n"
        "Generate a new -damon companion spirit based on a theme. Respond with valid JSON only.\n"
        "Required fields: name (snake_case, ends in 'damon' or 'mon'), displayName, flavor (1 poetic sentence), "
        "persona (1 sentence for LLM context), emoji (single emoji), "
        "glow ([R,G,B] 0-255 integers), sparkleColors ([[R,G,B],[R,G,B],[R,G,B]]), "
        "buff ({stat: string, magnitude: float 0-1, description: string}), "
        "signature_recipes ([\"Recipe 1\", \"Recipe 2\"]).\n"
        "Be creative. The game has a pastel Infinity Nikki aesthetic."
    )
    prompt = f"Theme: {theme}\nVoice style: {voice}\n\nGenerate the companion JSON:"

    try:
        with _semaphore:
            result = client.generate_json(prompt, system_prompt=system, temperature=0.8)
        if result and "name" in result:
            result["_offline"] = False
            return result
    except Exception as e:
        log.error("Companion generation failed: %s", e)

    return _offline_fallback_generate(theme)


def _companion_chat(companion_key: str, player_name: str, context: str, message: str) -> str:
    persona = _PERSONAS.get(companion_key)
    if not persona:
        persona = f"You are {companion_key}, a friendly cooking companion spirit in Zundamon's Kitchen."

    if not OLLAMA_AVAILABLE:
        return _offline_fallback_chat(companion_key)

    client = OllamaClient(model=MODEL_PRESETS.get("dialogue", "gemma4:12b"))
    if not client.is_available():
        return _offline_fallback_chat(companion_key)

    system = (
        f"{persona}\n\n"
        "Rules:\n"
        "- Stay in character at all times.\n"
        "- Reply in 1–3 sentences maximum (keep under ~2.5s speech length).\n"
        "- Do not break the fourth wall or mention Roblox.\n"
        "- If the companion speaks Japanese, use natural casual Japanese.\n"
        "- If asked something dangerous or off-topic, deflect in character.\n"
    )

    context_block = f"[Game context: {context[:400]}]\n" if context else ""
    prompt = f"{context_block}Player {player_name} says: {message}"

    try:
        with _semaphore:
            reply = client.generate(prompt, system_prompt=system, temperature=0.75, max_tokens=150)
        return reply.strip() if reply.strip() else _offline_fallback_chat(companion_key)
    except Exception as e:
        log.error("Companion chat failed: %s", e)
        return _offline_fallback_chat(companion_key)


# ── HTTP Handler ──────────────────────────────────────────────────────────────

class Handler(BaseHTTPRequestHandler):
    def log_message(self, format, *args):  # noqa: A002
        log.info("%s - %s", self.address_string(), format % args)

    def _send_json(self, code: int, data: Any):
        body = json.dumps(data, ensure_ascii=False).encode("utf-8")
        self.send_response(code)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _read_json(self) -> Dict[str, Any]:
        length = int(self.headers.get("Content-Length", 0))
        if length == 0:
            return {}
        raw = self.rfile.read(length)
        return json.loads(raw.decode("utf-8"))

    def do_GET(self):
        if self.path == "/health":
            self._send_json(200, {
                "status": "ok",
                "ollama_available": OLLAMA_AVAILABLE,
                "companions_loaded": len(_PERSONAS),
                "timestamp": int(time.time()),
            })
        else:
            self._send_json(404, {"error": "Not found"})

    def do_POST(self):
        try:
            body = self._read_json()
        except Exception:
            self._send_json(400, {"error": "Invalid JSON body"})
            return

        if self.path == "/generate-companion":
            theme = str(body.get("theme", "mystery spirit"))[:200]
            voice = str(body.get("voice", "normal"))
            try:
                result = _generate_companion(theme, voice)
                self._send_json(200, result)
            except Exception:
                log.error(traceback.format_exc())
                self._send_json(200, _offline_fallback_generate(theme))

        elif self.path == "/companion-chat":
            companion_key = str(body.get("companion_key", "zundamon"))
            player_name   = str(body.get("player_name", "Player"))[:50]
            context       = str(body.get("context", ""))[:400]
            message       = str(body.get("message", ""))[:300]
            if not message.strip():
                self._send_json(400, {"error": "message is required"})
                return
            try:
                reply = _companion_chat(companion_key, player_name, context, message)
                self._send_json(200, {"reply": reply})
            except Exception:
                log.error(traceback.format_exc())
                self._send_json(200, {"reply": _offline_fallback_chat(companion_key)})

        else:
            self._send_json(404, {"error": "Unknown endpoint"})

    def do_OPTIONS(self):
        # CORS preflight — not needed for Roblox HttpService but harmless
        self.send_response(204)
        self.end_headers()


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Companion AI Bridge Server")
    parser.add_argument("--host", default="127.0.0.1", help="Bind address (default: 127.0.0.1)")
    parser.add_argument("--port", type=int, default=8742, help="Port (default: 8742)")
    args = parser.parse_args()

    log.info("=" * 60)
    log.info("Companion AI Bridge — Zundamon's Kitchen V2")
    log.info("  Listening on http://%s:%d", args.host, args.port)
    log.info("  Ollama client:  %s", "loaded" if OLLAMA_AVAILABLE else "NOT FOUND (offline mode)")
    log.info("  Personas:       %d companions", len(_PERSONAS))
    log.info("  Endpoints:      GET /health  POST /generate-companion  POST /companion-chat")
    log.info("  See docs/LLM_PIPELINE.md for setup instructions.")
    log.info("=" * 60)

    server = HTTPServer((args.host, args.port), Handler)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        log.info("Shutting down.")
        server.server_close()


if __name__ == "__main__":
    main()
