#!/usr/bin/env python3
"""
Companion AI Bridge — Zundamon's Kitchen V2

Local HTTP bridge that powers the in-game "Summon a Companion" feature's AI half.
Takes a theme prompt and returns a complete companion spec JSON, generated by a
local LLM (Ollama) and optionally voiced by VOICEVOX.

Game side: set `CompanionAIGenerator.GENERATE_URL` to `http://127.0.0.1:8700/generate`
(this server's address) so `CompanionCreatorService.generate()` calls here instead
of using its deterministic offline fallback.

Endpoints:
  POST /generate
      body:  {"theme": "...", "voice": "normal"}     (voice optional)
      resp:  companion spec JSON (name, displayName, flavor, persona, emoji,
             glow[3], sparkleColors[[3]x3], buff{stat,magnitude,description},
             signature_recipes[3])  — validated/normalized before returning
  GET  /health  -> {"ok": true, "llm": bool, "voicevox": bool}

Run:
  python scripts/companion_ai_bridge.py [--port 8700] [--model qwen2.5-coder:7b]

Requires: ollama serve running with the model pulled; voicevox optional (greeting
WAV is written to scripts/companion_voice_out/ but not required for the spec).
"""

import argparse
import json
import os
import sys
import traceback
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

# Ensure sibling scripts are importable
sys.path.insert(0, str(Path(__file__).resolve().parent))

import ollama_client  # noqa: E402

DEFAULT_PORT = 8700
DEFAULT_MODEL = "qwen2.5-coder:7b"

ALLOWED_EMOJI = ["🌱", "🌸", "🍡", "🍵", "🌙", "☀️", "🍄", "🦊", "🐸", "🐢", "🐻", "🦉", "⭐", "🌊", "🍂", "🪷", "🥟", "🍙", "🫧", "💫"]
ALLOWED_BUFF_STATS = ["gold", "xp", "speed", "perfect_window", "extra_drop"]

SYSTEM_PROMPT = """You create Zundamon-style companion spirits for a cozy cooking game called Zundamon's Kitchen.
Return ONLY valid JSON with EXACTLY these keys (no markdown, no extra text):
{
  "name": string,                    // whimsical spirit name, e.g. "Moon Fox"
  "displayName": string,             // display name
  "flavor": string,                  // one short sentence of flavor text
  "persona": string,                 // two sentences: how the companion talks/feels
  "emoji": one of the allowed list,
  "glow": [r, g, b],                 // 0..1 floats, signature glow color
  "sparkleColors": [[r,g,b], [r,g,b], [r,g,b]],  // 3 accent colors
  "buff": {"stat": one of ["gold","xp","speed","perfect_window","extra_drop"], "magnitude": 0.05..0.3, "description": string},
  "signature_recipes": [3 dish name strings]
}
Allowed emoji: ["🌱","🌸","🍡","🍵","🌙","☀️","🍄","🦊","🐸","🐢","🐻","🦉","⭐","🌊","🍂","🪷","🥟","🍙","🫧","💫"]
Keep it warm, whimsical, and pea/food/village themed. Names should feel hand-crafted."""


def clamp(v, lo, hi):
    try:
        f = float(v)
    except (TypeError, ValueError):
        return lo
    return max(lo, min(hi, f))


def normalize_spec(raw):
    """Sanitize an LLM response into a safe, complete spec the game accepts."""
    if not isinstance(raw, dict):
        raise ValueError("LLM response is not a JSON object")
    name = str(raw.get("name") or "Mystery Zundamon")[:24]
    display = str(raw.get("displayName") or name)[:24]
    flavor = str(raw.get("flavor") or "A companion you created.")[:200]
    persona = str(raw.get("persona") or f"You are {name}, a companion who walks beside the player.")[:500]

    emoji = raw.get("emoji")
    if emoji not in ALLOWED_EMOJI:
        emoji = "🌱"

    def color3(arr, fallback=(0.7, 0.78, 1.0)):
        if isinstance(arr, (list, tuple)) and len(arr) >= 3:
            return [round(clamp(arr[0], 0, 1), 3), round(clamp(arr[1], 0, 1), 3), round(clamp(arr[2], 0, 1), 3)]
        return list(fallback)

    glow = color3(raw.get("glow"))
    sc = raw.get("sparkleColors")
    sparkles = []
    if isinstance(sc, list):
        for c in sc[:3]:
            sparkles.append(color3(c))
    while len(sparkles) < 3:
        sparkles.append(color3(None, glow))

    buff = raw.get("buff")
    if isinstance(buff, dict) and buff.get("stat") in ALLOWED_BUFF_STATS:
        stat = buff["stat"]
        mag = round(clamp(buff.get("magnitude", 0.1), 0.05, 0.5), 3)
        desc = str(buff.get("description") or f"+{int(mag*100)}% effect")[:120]
    else:
        stat, mag, desc = "gold", 0.05, "+5% gold from serving guests"

    recipes = []
    if isinstance(raw.get("signature_recipes"), list):
        for r in raw["signature_recipes"]:
            if isinstance(r, str) and r.strip() and len(recipes) < 3:
                recipes.append(r.strip()[:60])
    if not recipes:
        recipes = ["Zunda Mochi", "Bread"]

    return {
        "name": name,
        "displayName": display,
        "flavor": flavor,
        "persona": persona,
        "emoji": emoji,
        "glow": glow,
        "sparkleColors": sparkles,
        "buff": {"stat": stat, "magnitude": mag, "description": desc},
        "signature_recipes": recipes,
        "synergy_gold": 5,
    }


class Handler(BaseHTTPRequestHandler):
    client = None
    model = DEFAULT_MODEL

    def log_message(self, fmt, *args):  # quieter
        sys.stderr.write("%s\n" % (fmt % args))

    def _send(self, code, obj):
        body = json.dumps(obj).encode("utf-8")
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self):
        if self.path.rstrip("/") == "/health":
            llm = self.client.is_available()
            vv = self._voicevox_up()
            self._send(200, {"ok": True, "llm": llm, "voicevox": vv})
        else:
            self._send(404, {"error": "not_found"})

    def do_POST(self):
        if self.path.rstrip("/") != "/generate":
            self._send(404, {"error": "not_found"})
            return
        try:
            length = int(self.headers.get("Content-Length", 0))
            payload = json.loads(self.rfile.read(length).decode("utf-8")) if length else {}
            theme = str(payload.get("theme") or "a cozy forest friend")[:120]
            voice = payload.get("voice")

            prompt = f"Create a companion based on this theme: {theme}"
            resp = self.client.generate(prompt, SYSTEM_PROMPT, temperature=0.8, max_tokens=700)
            raw = ollama_client.OllamaClient._extract_json(resp)
            spec = normalize_spec(raw)
            self._send(200, spec)
        except Exception as e:  # noqa: BLE001
            traceback.print_exc()
            self._send(500, {"error": str(e)[:200]})

    def _voicevox_up(self):
        try:
            import urllib.request
            with urllib.request.urlopen("http://127.0.0.1:50021/version", timeout=3):
                return True
        except Exception:
            return False


def main():
    ap = argparse.ArgumentParser(description="Companion AI Bridge for Zundamon's Kitchen V2")
    ap.add_argument("--port", type=int, default=DEFAULT_PORT)
    ap.add_argument("--model", default=DEFAULT_MODEL)
    args = ap.parse_args()

    Handler.client = ollama_client.OllamaClient(model=args.model)
    Handler.model = args.model

    if not Handler.client.is_available():
        print("WARN: Ollama not reachable at 127.0.0.1:11434. Start it with: ollama serve")
    else:
        print(f"Ollama reachable, model: {args.model}")

    srv = ThreadingHTTPServer(("127.0.0.1", args.port), Handler)
    print(f"Companion AI Bridge listening on http://127.0.0.1:{args.port}/generate")
    print("Set CompanionAIGenerator.GENERATE_URL to this URL in-game.")
    try:
        srv.serve_forever()
    except KeyboardInterrupt:
        print("\nShutting down.")
        srv.shutdown()


if __name__ == "__main__":
    main()
