#!/usr/bin/env python3
"""
Emit Damon Texture Config — Zundamon's Kitchen V2
==================================================

Reads scripts/damon_textures/manifest.json and emits
src/shared/ConfigurationFiles/DamonTextureConfig.lua.

Usage:
    python scripts/emit_damon_texture_config.py           # generate
    python scripts/emit_damon_texture_config.py --check   # CI: fail if stale
"""

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

SCRIPTS_DIR = Path(__file__).parent
REPO_ROOT = SCRIPTS_DIR.parent
MANIFEST = SCRIPTS_DIR / "damon_textures" / "manifest.json"
OUTPUT_LUA = REPO_ROOT / "src" / "shared" / "ConfigurationFiles" / "DamonTextureConfig.lua"

HEADER = """\
--!strict
-- [[ModuleScript] DamonTextureConfig]]
-- AUTO-GENERATED by scripts/emit_damon_texture_config.py
-- DO NOT HAND-EDIT. Re-run the script to regenerate.
--
-- Maps companion keys to their uploaded Roblox decal asset IDs.
-- An empty string means the texture has not been uploaded yet —
-- the UI falls back to the companion's glow color field.
--
-- Pipeline:
--   1. Generate:  python scripts/damon_texture_gen.py --all
--   2. Upload:    python scripts/damon_texture_upload.py --all
--   3. Emit:      python scripts/emit_damon_texture_config.py
--   See docs/TEXTURE_PIPELINE.md for the full guide.

local DamonTextureConfig = {}

DamonTextureConfig.textures = {
"""

FOOTER = """\
}

-- Returns the rbxassetid URI for a companion key, or "" if not uploaded yet.
function DamonTextureConfig.getTexture(key: string): string
\treturn DamonTextureConfig.textures[key] or ""
end

-- Returns true if a companion has an uploaded texture.
function DamonTextureConfig.hasTexture(key: string): boolean
\tlocal t = DamonTextureConfig.textures[key]
\treturn t ~= nil and t ~= ""
end

return DamonTextureConfig
"""


def load_manifest():
    if not MANIFEST.exists():
        print(f"[ERROR] Manifest not found: {MANIFEST}")
        print("Run: python scripts/damon_texture_gen.py --all")
        sys.exit(1)
    with open(MANIFEST, "r", encoding="utf-8") as f:
        return json.load(f)


def stylua_format(text: str) -> str:
    """Run the generated source through StyLua."""
    if not shutil.which("stylua"):
        print("WARNING: stylua not on PATH — emitting unformatted (gate may fail)")
        return text

    tmp_dir = tempfile.mkdtemp()
    tmp = os.path.join(tmp_dir, "DamonTextureConfig.lua")
    try:
        with open(tmp, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        proc = subprocess.run(
            ["stylua", "--config-path", str(REPO_ROOT / "stylua.toml"), tmp],
            capture_output=True,
            text=True,
        )
        if proc.returncode != 0:
            print(f"WARNING: stylua failed ({proc.stderr.strip()[:160]}) — emitting raw")
            return text
        with open(tmp, encoding="utf-8", newline="") as f:
            return f.read().replace("\r\n", "\n")
    finally:
        shutil.rmtree(tmp_dir, ignore_errors=True)


def build_lua(manifest: dict) -> str:
    lines = [HEADER]
    for key in sorted(manifest.keys()):
        asset_id = manifest[key] or ""
        if asset_id and not asset_id.startswith("rbxassetid://"):
            asset_id = f"rbxassetid://{asset_id}"
        lines.append(f'\t{key} = "{asset_id}",\n')
    lines.append(FOOTER)
    return stylua_format("".join(lines))


def main():
    parser = argparse.ArgumentParser(description="Emit DamonTextureConfig.lua from manifest")
    parser.add_argument("--check", action="store_true", help="CI mode: fail if output would differ from disk")
    args = parser.parse_args()

    manifest = load_manifest()
    new_content = build_lua(manifest)

    if args.check:
        if not OUTPUT_LUA.exists():
            print(f"[FAIL] DamonTextureConfig.lua does not exist. Run: python scripts/emit_damon_texture_config.py")
            sys.exit(1)
        existing = OUTPUT_LUA.read_text(encoding="utf-8").replace("\r\n", "\n")
        if existing != new_content:
            print("[FAIL] DamonTextureConfig.lua is stale. Re-run: python scripts/emit_damon_texture_config.py")
            sys.exit(1)
        print(f"[OK] DamonTextureConfig.lua is up to date ({len(manifest)} entries).")
    else:
        with open(OUTPUT_LUA, "w", encoding="utf-8", newline="\n") as f:
            f.write(new_content)
        print(f"[OK] Written: {OUTPUT_LUA}")
        print(f"     {len(manifest)} companion entries ({sum(1 for v in manifest.values() if v)} uploaded).")


if __name__ == "__main__":
    main()
