
#!/usr/bin/env python3
"""
Extract asset IDs from Roblox place files (.rbxlx) and format for AssetRegistry.lua
Usage: python extract_asset_ids.py place.rbxlx [output.lua]
"""

import re
import sys
import os
from pathlib import Path
from typing import Dict, List, Tuple
from collections import defaultdict

def extract_assets_from_rbxlx(file_path: str) -> List[str]:
    """Extract all unique asset IDs from a .rbxlx file."""
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Find all rbxassetid:// patterns
    pattern = r'rbxassetid://(\d+)'
    matches = re.findall(pattern, content)
    
    # Return unique IDs while preserving order
    seen = set()
    unique = []
    for asset_id in matches:
        if asset_id not in seen:
            seen.add(asset_id)
            unique.append(asset_id)
    
    return unique

def categorize_assets(asset_ids: List[str], content: str) -> Dict[str, List[str]]:
    """Attempt to categorize assets based on context in the XML."""
    categories = {
        'Meshes': [],
        'Textures': [],
        'Audio': [],
        'Particles': [],
        'Animations': []
    }
    
    for asset_id in asset_ids:
        # Find context around the asset ID
        pattern = rf'.{{0,100}}rbxassetid://{re.escape(asset_id)}.{{0,100}}'
        matches = re.findall(pattern, content, re.DOTALL)
        
        if matches:
            context = matches[0].lower()
            
            # Categorize based on context clues
            if any(keyword in context for keyword in ['mesh', 'meshpart', 'specialmesh', 'blockmesh']):
                categories['Meshes'].append(asset_id)
            elif any(keyword in context for keyword in ['texture', 'decall', 'surfacegui', 'image']):
                categories['Textures'].append(asset_id)
            elif any(keyword in context for keyword in ['sound', 'audio', 'music']):
                categories['Audio'].append(asset_id)
            elif any(keyword in context for keyword in ['particle', 'vfx', 'emitter']):
                categories['Particles'].append(asset_id)
            elif any(keyword in context for keyword in ['animation', 'anim']):
                categories['Animations'].append(asset_id)
            else:
                # Default to Meshes if unsure
                categories['Meshes'].append(asset_id)
        else:
            categories['Meshes'].append(asset_id)
    
    return categories

def generate_lua_registry(asset_ids: List[str], categories: Dict[str, List[str]]) -> str:
    """Generate Lua code for AssetRegistry.lua."""
    lua = '''--!strict
-- AssetRegistry: Single source of truth for all game assets and asset IDs
-- Auto-generated by extract_asset_ids.py
-- Source: Extracted from place.rbxlx

local AssetRegistry = {
	Name = "Zundamon's Kitchen V2 Asset Registry" :: string,
	Version = "1.0.0" :: string,
	LastUpdated = os.time() :: number,
'''

    # Add categorized assets
    if categories['Meshes']:
        lua += '\n\t-- 3D Meshes\n'
        lua += '\tMeshes = {\n'
        for asset_id in categories['Meshes']:
            lua += f'\t\t["{asset_id}"] = "rbxassetid://{asset_id}",\n'
        lua += '\t},\n'
    
    if categories['Textures']:
        lua += '\n\t-- UI Textures\n'
        lua += '\tTextures = {\n'
        for asset_id in categories['Textures']:
            lua += f'\t\t["{asset_id}"] = "rbxassetid://{asset_id}",\n'
        lua += '\t},\n'
    
    if categories['Audio']:
        lua += '\n\t-- Audio\n'
        lua += '\tAudio = {\n'
        for asset_id in categories['Audio']:
            lua += f'\t\t["{asset_id}"] = "rbxassetid://{asset_id}",\n'
        lua += '\t},\n'
    
    if categories['Particles']:
        lua += '\n\t-- Particles\n'
        lua += '\tParticles = {\n'
        for asset_id in categories['Particles']:
            lua += f'\t\t["{asset_id}"] = "rbxassetid://{asset_id}",\n'
        lua += '\t},\n'
    
    if categories['Animations']:
        lua += '\n\t-- Animations\n'
        lua += '\tAnimations = {\n'
        for asset_id in categories['Animations']:
            lua += f'\t\t["{asset_id}"] = "rbxassetid://{asset_id}",\n'
        lua += '\t},\n'
    
    # Add uncategorized assets
    uncategorized = set(asset_ids) - set(sum(categories.values(), []))
    if uncategorized:
        lua += '\n\t-- Uncategorized Assets\n'
        lua += '\tUncategorized = {\n'
        for asset_id in uncategorized:
            lua += f'\t\t["{asset_id}"] = "rbxassetid://{asset_id}",\n'
        lua += '\t},\n'
    
    # Add API functions (simplified)
    lua += '''
-- AssetRegistry API
local AssetRegistry = {}

function AssetRegistry.Get(category: string, subcategory: string, assetName: string): string
	return "" -- TODO: Implement lookup
end

function AssetRegistry.Set(category: string, subcategory: string, assetName: string, assetId: string): ()
	-- TODO: Implement setter
end

function AssetRegistry.Validate(): {string}
	return {} -- TODO: Implement validation
end

function AssetRegistry.GetMissingIDs(): {string}
	return {} -- TODO: Implement missing ID check
end

return AssetRegistry
'''
    
    return lua

def main():
    if len(sys.argv) < 2:
        print("Usage: python extract_asset_ids.py <place.rbxlx> [output.lua]")
        sys.exit(1)
    
    input_file = sys.argv[1]
    output_file = sys.argv[2] if len(sys.argv) > 2 else "src/shared/AssetRegistry.lua"
    
    if not os.path.exists(input_file):
        print(f"Error: File not found: {input_file}")
        sys.exit(1)
    
    print(f"Extracting assets from: {input_file}")
    
    # Extract assets
    asset_ids = extract_assets_from_rbxlx(input_file)
    print(f"Found {len(asset_ids)} unique asset IDs")
    
    if not asset_ids:
        print("Warning: No asset IDs found in file")
        sys.exit(0)
    
    # Categorize
    with open(input_file, 'r', encoding='utf-8') as f:
        content = f.read()
    categories = categorize_assets(asset_ids, content)
    
    # Print summary
    print("\nAsset breakdown:")
    for category, ids in categories.items():
        if ids:
            print(f"  {category}: {len(ids)} assets")
    
    # Generate Lua code
    lua_code = generate_lua_registry(asset_ids, categories)
    
    # Write output
    output_path = Path(output_file)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(lua_code)
    
    print(f"\nGenerated AssetRegistry.lua at: {output_path}")
    print("\nNext steps:")
    print("1. Review the generated AssetRegistry.lua")
    print("2. Rename generic asset IDs to meaningful names")
    print("3. Move assets into proper category subfolders")
    print("4. Test in Roblox Studio")

if __name__ == "__main__":
    main()