-- [[LocalScript] LocalTools (ref: RBX51B35FCBF01947F8BAB60016A1D5A51B)]
-- DISABLED: Conflicts with ToolClient.client.lua (both invoke ConnectFunction).
-- ToolClient uses the modern Tool.Activated pattern; this legacy script used
-- CollectionService + mouse-hold loop, causing double-invocations per click.
